import type { ExpectedCapability, ProductProfile, ProductProfileDefinition } from './types';

function capability(args: ExpectedCapability): ExpectedCapability {
  return args;
}

const shared = {
  authRequired: capability({
    id: 'auth.baseline',
    title: 'Authentication baseline',
    category: 'auth',
    importance: 'required',
    detectorKeys: ['auth.core'],
    description: 'The product profile expects authenticated users and explicit auth flow controls.',
    recommendation: 'Implement robust authentication flow and protect user-facing routes.',
  }),
  authzRecommended: capability({
    id: 'authz.resource-level',
    title: 'Resource-level authorization',
    category: 'authz',
    importance: 'recommended',
    detectorKeys: ['authz.resourceLevel', 'authz.permissions', 'authz.roles'],
    description: 'Role or permission checks should be present for protected resources.',
    recommendation: 'Add policy checks for read, update, and delete actions.',
  }),
  authzRequired: capability({
    id: 'authz.resource-level',
    title: 'Resource-level authorization',
    category: 'authz',
    importance: 'required',
    detectorKeys: ['authz.resourceLevel', 'authz.permissions', 'authz.roles'],
    description: 'The profile expects resource-scoped authorization checks.',
    recommendation: 'Add policy checks and ownership checks to prevent IDOR-style access.',
  }),
  tenancyRequired: capability({
    id: 'tenancy.model',
    title: 'Tenant or organization boundaries',
    category: 'tenancy',
    importance: 'required',
    detectorKeys: ['tenancy.organization', 'tenancy.membership'],
    description: 'The profile expects explicit tenant or organization boundaries.',
    recommendation: 'Model organization and membership explicitly and scope all access by tenant context.',
  }),
  gdprRequired: capability({
    id: 'gdpr.baseline',
    title: 'Privacy and GDPR baseline',
    category: 'gdpr',
    importance: 'required',
    detectorKeys: ['gdpr.consent.route', 'gdpr.export.route', 'gdpr.erasure.route', 'gdpr.retention.job'],
    description: 'The profile expects explicit privacy controls and user-data workflows.',
    recommendation: 'Add consent, export, erasure, and retention workflows with auditability.',
  }),
  gdprRecommended: capability({
    id: 'gdpr.baseline',
    title: 'Privacy and GDPR baseline',
    category: 'gdpr',
    importance: 'recommended',
    detectorKeys: ['gdpr.consent.route', 'gdpr.export.route', 'gdpr.erasure.route', 'gdpr.retention.job'],
    description: 'The profile may need privacy controls depending on user data handling.',
    recommendation: 'Add privacy workflows where personal data is stored or processed.',
  }),
  securityHeadersRequired: capability({
    id: 'security.headers',
    title: 'Security headers middleware',
    category: 'security',
    importance: 'required',
    detectorKeys: ['security.core'],
    description: 'The profile expects security header middleware for browser-facing APIs and apps.',
    recommendation: 'Mount helmet (or equivalent) and review CSP/HSTS settings.',
  }),
  securityHeadersRecommended: capability({
    id: 'security.headers',
    title: 'Security headers middleware',
    category: 'security',
    importance: 'recommended',
    detectorKeys: ['security.core'],
    description: 'Security header middleware is recommended for this profile.',
    recommendation: 'Mount helmet (or equivalent) and review CSP/HSTS settings.',
  }),
  corsRequired: capability({
    id: 'security.cors',
    title: 'CORS origin restrictions',
    category: 'security',
    importance: 'required',
    detectorKeys: ['security.core'],
    description: 'The profile expects explicit CORS allowlists in production.',
    recommendation: 'Use explicit origins from configuration and reject unknown origins.',
  }),
  corsRecommended: capability({
    id: 'security.cors',
    title: 'CORS origin restrictions',
    category: 'security',
    importance: 'recommended',
    detectorKeys: ['security.core'],
    description: 'CORS hardening is recommended for this profile.',
    recommendation: 'Use explicit origins from configuration and avoid wildcard defaults.',
  }),
  rateLimitRequired: capability({
    id: 'security.rate-limit',
    title: 'Auth/risk surface rate limiting',
    category: 'security',
    importance: 'required',
    detectorKeys: ['security.core'],
    description: 'The profile expects explicit request throttling on high-risk routes.',
    recommendation: 'Apply route-specific rate limits to auth and sensitive endpoints.',
  }),
  observabilityHealthRecommended: capability({
    id: 'observability.health',
    title: 'Health endpoint',
    category: 'observability',
    importance: 'recommended',
    detectorKeys: ['observability.core'],
    description: 'Health endpoints are recommended for runtime diagnostics and orchestration.',
    recommendation: 'Add /health or /healthz endpoint.',
  }),
  observabilityHealthRequired: capability({
    id: 'observability.health',
    title: 'Health endpoint',
    category: 'observability',
    importance: 'required',
    detectorKeys: ['observability.core'],
    description: 'This profile expects operational health endpoint coverage.',
    recommendation: 'Add /health or /healthz endpoint.',
  }),
  observabilityLoggingRecommended: capability({
    id: 'observability.logging',
    title: 'Structured logging',
    category: 'observability',
    importance: 'recommended',
    detectorKeys: ['observability.core'],
    description: 'Structured logging is recommended for traceability and supportability.',
    recommendation: 'Adopt structured logger and request correlation ids.',
  }),
  observabilityLoggingRequired: capability({
    id: 'observability.logging',
    title: 'Structured logging',
    category: 'observability',
    importance: 'required',
    detectorKeys: ['observability.core'],
    description: 'This profile expects strong runtime logging and request correlation.',
    recommendation: 'Adopt structured logger and request correlation ids.',
  }),
  deploymentRequired: capability({
    id: 'deployment.readiness',
    title: 'Deployment readiness',
    category: 'deployment',
    importance: 'required',
    detectorKeys: ['deployment.readiness'],
    description: 'The profile expects reproducible deployment and runtime readiness signals.',
    recommendation: 'Add deploy artifacts, graceful shutdown, and production-aware runtime settings.',
  }),
  deploymentRecommended: capability({
    id: 'deployment.readiness',
    title: 'Deployment readiness',
    category: 'deployment',
    importance: 'recommended',
    detectorKeys: ['deployment.readiness'],
    description: 'Deployment artifacts are recommended for this profile.',
    recommendation: 'Add deploy artifacts and production-aware runtime settings.',
  }),
  dockerRecommended: capability({
    id: 'deployment.docker',
    title: 'Container packaging',
    category: 'deployment',
    importance: 'recommended',
    detectorKeys: ['infra.docker'],
    description: 'Container packaging is recommended for reproducibility.',
    recommendation: 'Add Dockerfile and optionally Compose for local and CI parity.',
  }),
  uploadsRequired: capability({
    id: 'uploads.protection',
    title: 'Upload route protection',
    category: 'uploads',
    importance: 'required',
    detectorKeys: ['uploads.exposure'],
    description: 'When uploads exist, the profile expects protected upload surfaces.',
    recommendation: 'Protect upload routes and enforce validation for file size and type.',
  }),
  billingRecommended: capability({
    id: 'billing.baseline',
    title: 'Billing/subscription baseline',
    category: 'billing',
    importance: 'recommended',
    detectorKeys: ['billing.stripe'],
    description: 'SaaS profile generally benefits from explicit billing capability.',
    recommendation: 'Introduce plan/subscription model and entitlement checks.',
  }),
  billingRequired: capability({
    id: 'billing.baseline',
    title: 'Billing/subscription baseline',
    category: 'billing',
    importance: 'required',
    detectorKeys: ['billing.stripe'],
    description: 'Marketplace profile expects explicit billing and entitlement capability.',
    recommendation: 'Introduce plan/subscription model, entitlement checks, and payment workflows.',
  }),
  auditRecommended: capability({
    id: 'audit.baseline',
    title: 'Audit logging for sensitive actions',
    category: 'audit',
    importance: 'recommended',
    detectorKeys: ['observability.core', 'auth.core', 'billing.stripe'],
    description: 'Sensitive actions should be auditable for support, compliance, and investigations.',
    recommendation: 'Log actor/action/target/timestamp/request id for sensitive events.',
  }),
  jobsRecommended: capability({
    id: 'jobs.background',
    title: 'Background jobs or queue processing',
    category: 'jobs',
    importance: 'recommended',
    detectorKeys: ['jobs.background'],
    description: 'AI-heavy products usually need queue or job orchestration for async processing.',
    recommendation: 'Introduce queue/background jobs for non-blocking and retriable workloads.',
  }),
  apiKeyRecommended: capability({
    id: 'auth.api-keys',
    title: 'API key support for service access',
    category: 'auth',
    importance: 'recommended',
    detectorKeys: ['auth.apiKeys'],
    description: 'AI SaaS often requires API key-based service access controls.',
    recommendation: 'Add API key issuance, validation, rotation, and scope policies.',
  }),
};

export const productProfiles: Record<Exclude<ProductProfile, 'auto' | 'observed-only'>, ProductProfileDefinition> = {
  'static-site': {
    id: 'static-site',
    title: 'Static Site',
    description: 'Static or primarily frontend site with minimal backend requirements.',
    capabilities: [
      { ...shared.authRequired, importance: 'not_applicable' },
      { ...shared.authzRecommended, importance: 'not_applicable' },
      { ...shared.tenancyRequired, importance: 'not_applicable' },
      { ...shared.billingRequired, importance: 'not_applicable' },
      { ...shared.gdprRecommended, importance: 'optional' },
      { ...shared.corsRecommended, importance: 'optional' },
      { ...shared.observabilityHealthRecommended, importance: 'optional' },
      shared.deploymentRecommended,
    ],
  },
  'internal-tool': {
    id: 'internal-tool',
    title: 'Internal Tool',
    description: 'Operational tool for internal users with moderate security and operability expectations.',
    capabilities: [
      shared.authRequired,
      shared.authzRecommended,
      shared.securityHeadersRecommended,
      shared.corsRecommended,
      shared.observabilityHealthRecommended,
      shared.observabilityLoggingRecommended,
      shared.deploymentRecommended,
      shared.gdprRecommended,
      { ...shared.tenancyRequired, importance: 'optional' },
      { ...shared.billingRecommended, importance: 'not_applicable' },
    ],
  },
  'b2c-app': {
    id: 'b2c-app',
    title: 'B2C App',
    description: 'Consumer-facing app with user accounts and privacy/security baseline requirements.',
    capabilities: [
      shared.authRequired,
      shared.authzRecommended,
      shared.gdprRequired,
      shared.securityHeadersRequired,
      shared.corsRequired,
      shared.rateLimitRequired,
      shared.observabilityHealthRecommended,
      shared.observabilityLoggingRecommended,
      shared.deploymentRequired,
      { ...shared.billingRecommended, importance: 'optional' },
      { ...shared.tenancyRequired, importance: 'not_applicable' },
    ],
  },
  'b2b-saas': {
    id: 'b2b-saas',
    title: 'B2B SaaS',
    description: 'Business SaaS product with tenancy, authorization depth, privacy, and operability expectations.',
    capabilities: [
      shared.authRequired,
      shared.authzRequired,
      shared.tenancyRequired,
      shared.gdprRequired,
      shared.securityHeadersRequired,
      shared.corsRequired,
      shared.rateLimitRequired,
      shared.uploadsRequired,
      shared.billingRecommended,
      shared.observabilityHealthRequired,
      shared.observabilityLoggingRecommended,
      shared.deploymentRequired,
      shared.dockerRecommended,
      shared.auditRecommended,
    ],
  },
  'ai-saas': {
    id: 'ai-saas',
    title: 'AI SaaS',
    description: 'AI-powered SaaS with async workloads, upload safety, strict security, and high observability expectations.',
    capabilities: [
      shared.authRequired,
      shared.authzRequired,
      shared.tenancyRequired,
      shared.gdprRequired,
      shared.securityHeadersRequired,
      shared.corsRequired,
      shared.rateLimitRequired,
      shared.uploadsRequired,
      shared.billingRecommended,
      shared.observabilityHealthRequired,
      shared.observabilityLoggingRequired,
      shared.deploymentRequired,
      shared.dockerRecommended,
      shared.jobsRecommended,
      shared.apiKeyRecommended,
      shared.auditRecommended,
    ],
  },
  marketplace: {
    id: 'marketplace',
    title: 'Marketplace',
    description: 'Two-sided or multi-role product requiring strong authz, billing, privacy, and operations controls.',
    capabilities: [
      shared.authRequired,
      shared.authzRequired,
      shared.tenancyRequired,
      shared.billingRequired,
      shared.gdprRequired,
      shared.auditRecommended,
      shared.securityHeadersRequired,
      shared.rateLimitRequired,
      shared.observabilityHealthRequired,
      shared.observabilityLoggingRequired,
      shared.deploymentRequired,
      shared.dockerRecommended,
    ],
  },
};

export function getProductProfile(profile: Exclude<ProductProfile, 'auto' | 'observed-only'>): ProductProfileDefinition {
  return productProfiles[profile];
}