plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.acme.sync'
    compileSdk 34
}

dependencies {
    implementation "com.livinglifetechway:quickpermissions-kotlin:0.5.1"
    implementation 'androidx.activity:activity-compose:1.9.0'
    implementation 'com.google.accompanist:accompanist-permissions:0.34.0'
}
