import type { RemediationCatalogEntry, RemediationPhaseId } from './types';

function entry(overrides: RemediationCatalogEntry): RemediationCatalogEntry {
  return overrides;
}

const critical: RemediationPhaseId = 'critical-blockers';
const safety: RemediationPhaseId = 'saas-safety-layer';
const ops: RemediationPhaseId = 'operational-readiness';

export const remediationCatalog: Record<string, RemediationCatalogEntry> = {
  'security.weak-secret': entry({
    taskId: 'remediate.security.weak-secret',
    title: 'Remove fallback secrets and enforce startup validation',
    category: 'security',
    phaseId: critical,
    priority: 'p0',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'safe_template',
    why: 'Fallback secrets allow production to boot with insecure defaults and can silently weaken signing or session protection.',
    recommendedApproach: [
      'Remove fallback values for JWT_SECRET, SESSION_SECRET, SECRET_KEY, and similar signing material.',
      'Fail fast during startup when required secrets are missing in production.',
      'Update .env.example with safe placeholders only.',
      'Add tests for missing-secret startup failure and placeholder-only examples.',
    ].join('\n'),
    likelyFiles: ['.env.example', 'backend/server.js', 'backend/config/*', 'src/server.ts'],
    suggestedTests: [
      'Startup fails when required secret env vars are missing.',
      '.env.example contains placeholders only.',
      'No config path falls back to a hardcoded signing secret.',
    ],
    acceptanceCriteria: [
      'No weak fallback secret remains.',
      'App fails on production startup if a required secret is missing.',
      '.env.example documents required secret keys without real values.',
    ],
    dependencies: ['remediate.env.example'],
  }),
  'security.cors-origin': entry({
    taskId: 'remediate.security.cors-origin',
    title: 'Lock CORS to explicit allowed origins',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'safe_template',
    why: 'Permissive CORS can expose authenticated browser flows to unwanted cross-origin access.',
    recommendedApproach: [
      'Replace cors() defaults with an explicit allowlist.',
      'Drive allowed origins from environment variables.',
      'Reject unknown origins in production.',
    ].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/config/*', 'src/server.ts', '.env.example'],
    suggestedTests: [
      'Production CORS is not wildcard or permissive.',
      'Allowed origins are sourced from configuration.',
      'Unexpected origins are rejected.',
    ],
    acceptanceCriteria: [
      'Production CORS is not wildcard/permissive.',
      'Allowed origins are documented in .env.example.',
    ],
    dependencies: ['remediate.env.example'],
  }),
  'security.helmet': entry({
    taskId: 'remediate.security.helmet',
    title: 'Add security headers middleware',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Helmet-style security headers are a low-risk baseline that improves browser-side hardening quickly.',
    recommendedApproach: ['Install and mount helmet before routes.', 'Tune CSP and HSTS for the deployment model.'].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/app.js', 'src/server.ts', 'src/app.ts'],
    suggestedTests: [
      'Helmet is mounted before routes.',
      'Production responses include security headers.',
    ],
    acceptanceCriteria: [
      'Helmet is mounted before routes.',
      'Production security headers are present.',
    ],
    dependencies: [],
  }),
  'security.rate-limit-auth': entry({
    taskId: 'remediate.security.rate-limit-auth',
    title: 'Rate limit authentication surfaces',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Login and password-reset endpoints are common brute-force targets and should be throttled explicitly.',
    recommendedApproach: [
      'Apply auth-specific rate limiting to login, register, and password-reset routes.',
      'Avoid throttling unrelated API traffic.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/middleware/*', 'src/routes/auth*', 'src/middleware/*'],
    suggestedTests: [
      'Repeated login attempts are throttled.',
      'Normal API routes are not unintentionally blocked.',
    ],
    acceptanceCriteria: [
      'Repeated login attempts are throttled.',
      'Normal API routes remain usable.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'uploads.public-exposure': entry({
    taskId: 'remediate.uploads.public-exposure',
    title: 'Protect public upload routes',
    category: 'uploads',
    phaseId: critical,
    priority: 'p0',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'needs_review',
    why: 'Anonymous upload exposure can lead to data leakage, abuse, and content-type bypasses.',
    recommendedApproach: [
      'Protect the /uploads static route with auth middleware.',
      'Validate MIME type and extension.',
      'Enforce maximum upload size.',
      'Prefer private object storage or signed URLs over public disk exposure.',
    ].join('\n'),
    likelyFiles: ['backend/app.js', 'backend/server.js', 'backend/routes/uploads*', 'backend/middleware/auth*'],
    suggestedTests: [
      'Anonymous access to protected uploads is denied.',
      'Oversized or invalid MIME uploads are rejected.',
      'Authenticated upload flow still works.',
    ],
    acceptanceCriteria: [
      'Uploads are not publicly exposed without auth checks.',
      'Anonymous access is denied for protected uploads.',
      'Upload validation rejects invalid files.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'auth.core': entry({
    taskId: 'remediate.auth.core',
    title: 'Implement an explicit authentication baseline',
    category: 'auth',
    phaseId: critical,
    priority: 'p0',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'A clear auth baseline is the prerequisite for protected resources, rate limits, tenant scoping, and privacy workflows.',
    recommendedApproach: [
      'Add a clear auth flow and secure credential handling.',
      'Ensure auth state is backed by explicit middleware or framework primitives.',
      'Cover login, logout, and session handling with tests.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/middleware/auth*', 'src/auth*', 'src/middleware/*'],
    suggestedTests: [
      'Authenticated requests succeed and anonymous requests fail.',
      'Login/session setup is covered by tests.',
    ],
    acceptanceCriteria: [
      'Authentication flow is explicit and test-covered.',
      'Credentials and sessions are handled securely.',
    ],
    dependencies: [],
    supersededBy: ['expectation.auth.required', 'expectation.auth.password-reset.required', 'expectation.auth.email-verification.required', 'expectation.auth.mfa.required'],
  }),
  'billing.webhook-signature': entry({
    taskId: 'remediate.billing.webhook-signature',
    title: 'Harden Stripe webhook verification',
    category: 'billing',
    phaseId: critical,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Webhook processing without raw-body handling and signature checks can accept spoofed billing events.',
    recommendedApproach: [
      'Ensure the webhook route uses raw body handling before JSON parsing when required.',
      'Use STRIPE_WEBHOOK_SECRET from configuration.',
      'Validate stripe-signature with stripe.webhooks.constructEvent before processing events.',
      'Add tests for invalid and valid webhook signatures.',
    ].join('\n'),
    likelyFiles: ['backend/routes/webhook*', 'backend/server.js', 'backend/middleware/*', 'src/routes/*', '.env.example'],
    suggestedTests: [
      'Invalid Stripe signature returns 400.',
      'Valid Stripe event is accepted.',
      'Webhook parsing happens before JSON body parsing when required.',
    ],
    acceptanceCriteria: [
      'Invalid Stripe signature returns 400.',
      'Valid Stripe event is accepted.',
      'Webhook parsing uses the correct body mode for signature verification.',
    ],
    dependencies: ['remediate.env.example'],
  }),
  'billing.baseline': entry({
    taskId: 'remediate.billing.baseline',
    title: 'Add billing and subscription baseline',
    category: 'billing',
    phaseId: safety,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'The product profile expects explicit billing or entitlement capabilities.',
    recommendedApproach: [
      'Define plan and subscription model.',
      'Integrate billing provider or entitlement service.',
      'Add webhook validation if Stripe is used.',
      'Add tests for subscription state and feature gating.',
    ].join('\n'),
    likelyFiles: ['backend/routes/billing*', 'backend/models/*', 'backend/services/*', '.env.example'],
    suggestedTests: [
      'Subscription state updates are persisted correctly.',
      'Feature gates respect plan and subscription status.',
      'Webhook events are validated before state changes.',
    ],
    acceptanceCriteria: [
      'Plan and subscription model is defined.',
      'Feature entitlement checks are enforced.',
      'Billing state changes are test-covered.',
    ],
    dependencies: [],
  }),
  'tenancy.b2b': entry({
    taskId: 'remediate.tenancy.b2b',
    title: 'Introduce explicit tenant and organization boundaries',
    category: 'tenancy',
    phaseId: safety,
    priority: 'p1',
    effort: 'large',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'B2B signals without a tenant model create cross-tenant data leakage and authorization ambiguity.',
    recommendedApproach: [
      'Introduce Organization, Membership, and RoleAssignment models.',
      'Add tenant-context middleware.',
      'Scope queries by organizationId or tenantId.',
      'Add cross-tenant access tests.',
    ].join('\n'),
    likelyFiles: ['backend/models/*', 'backend/middleware/*', 'backend/routes/*', 'migrations/*', 'src/db/*'],
    suggestedTests: [
      'Tenant A cannot read, update, or delete Tenant B records.',
      'Tenant membership is explicit.',
      'Admin and owner roles are tenant-scoped.',
    ],
    acceptanceCriteria: [
      'User from tenant A cannot access tenant B records.',
      'Tenant membership is explicit.',
      'Admin and owner roles are tenant-scoped.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'authz.resource-level': entry({
    taskId: 'remediate.authz.resource-level',
    title: 'Add resource-level authorization checks',
    category: 'authz',
    phaseId: safety,
    priority: 'p1',
    effort: 'large',
    risk: 'high',
    automationReadiness: 'needs_review',
    why: 'Role-only authorization still allows IDOR-style access if resource ownership is not checked per object.',
    recommendedApproach: [
      'Introduce resource-level policy checks.',
      'Add ownership checks on read, update, and delete routes.',
      'Cover IDOR prevention with targeted tests.',
    ].join('\n'),
    likelyFiles: ['backend/routes/*', 'backend/services/*', 'src/routes/*', 'src/policies/*'],
    suggestedTests: [
      'Changing an ID in the URL cannot access another user\'s resource.',
      'Unauthorized update and delete return 403 or 404.',
    ],
    acceptanceCriteria: [
      'Changing an ID in the URL cannot access another user\'s resource.',
      'Unauthorized update and delete return 403 or 404.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'gdpr.privacy': entry({
    taskId: 'remediate.gdpr.privacy',
    title: 'Add privacy and GDPR control flows',
    category: 'gdpr',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'If users exist, privacy workflows need explicit consent, export, erasure, and retention handling.',
    recommendedApproach: [
      'Add consent tracking.',
      'Add a data export endpoint.',
      'Add erasure request or delete-account flow.',
      'Add retention policy documentation or a retention job.',
    ].join('\n'),
    likelyFiles: ['backend/routes/privacy*', 'backend/routes/export*', 'backend/jobs/*', 'backend/models/*', 'src/privacy*'],
    suggestedTests: [
      'Authenticated user can request an export of personal data.',
      'Erasure request is tracked.',
      'Privacy event is audited.',
    ],
    acceptanceCriteria: [
      'Authenticated user can request export of personal data.',
      'Erasure request is tracked.',
      'Privacy event is audited.',
    ],
    dependencies: ['remediate.auth.core'],
    supersededBy: ['expectation.gdpr.consent.required', 'expectation.gdpr.export.required', 'expectation.gdpr.erasure.required', 'expectation.gdpr.retention.recommended'],
  }),
  'observability.logging': entry({
    taskId: 'remediate.observability.logging',
    title: 'Add structured logging and request correlation',
    category: 'observability',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Structured logs and correlation ids make runtime troubleshooting and incident triage materially easier.',
    recommendedApproach: ['Add a structured logger.', 'Add request id or correlation id handling.', 'Centralize error logging.'].join('\n'),
    likelyFiles: ['backend/logger*', 'backend/middleware/*', 'src/logger*', 'src/middleware/*'],
    suggestedTests: [
      'Every request gets a request id.',
      'Server errors are logged with structured metadata.',
    ],
    acceptanceCriteria: [
      'Every request has a request id.',
      'Server errors are logged with structured metadata.',
    ],
    dependencies: [],
  }),
  'audit.baseline': entry({
    taskId: 'remediate.audit.baseline',
    title: 'Add audit logging for sensitive actions',
    category: 'audit',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Sensitive actions should be traceable for compliance, support, and incident response.',
    recommendedApproach: [
      'Log auth, billing, admin, privacy, and destructive actions.',
      'Capture actor, action, target, timestamp, and request id.',
      'Avoid storing sensitive payload data in audit events.',
    ].join('\n'),
    likelyFiles: ['backend/middleware/*', 'backend/services/*', 'backend/routes/*', 'src/middleware/*'],
    suggestedTests: [
      'Sensitive actions generate audit entries.',
      'Audit entries include actor/action/target/request id/timestamp.',
      'Sensitive payloads are not persisted in audit logs.',
    ],
    acceptanceCriteria: [
      'Sensitive actions are auditable.',
      'Audit entries contain required context fields.',
      'Sensitive payloads are excluded from audit logs.',
    ],
    dependencies: [],
  }),
  'observability.health': entry({
    taskId: 'remediate.observability.health',
    title: 'Add a runtime healthcheck endpoint',
    category: 'observability',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Health endpoints are a low-risk operational baseline for orchestration and deployment checks.',
    recommendedApproach: ['Add /health or /healthz and keep the response lightweight and deterministic.'].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/app.js', 'src/server.ts', 'src/app.ts'],
    suggestedTests: [
      'Health endpoint returns 200 in a healthy runtime.',
      'Health response stays deterministic and lightweight.',
    ],
    acceptanceCriteria: [
      'Healthcheck succeeds.',
      'Health endpoint is deterministic and lightweight.',
    ],
    dependencies: [],
  }),
  'deployment.readiness': entry({
    taskId: 'remediate.deployment.readiness',
    title: 'Add reproducible deployment assets',
    category: 'deployment',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'A reproducible deploy path reduces environment drift and makes operational behavior easier to verify.',
    recommendedApproach: [
      'Add a Dockerfile.',
      'Add docker-compose for local reproducibility when useful.',
      'Add healthcheck and graceful shutdown handling.',
      'Add production env validation.',
    ].join('\n'),
    likelyFiles: ['Dockerfile', 'docker-compose.yml', 'package.json', 'src/index.ts', 'backend/server.js'],
    suggestedTests: [
      'App can be started reproducibly.',
      'Healthcheck succeeds.',
      'SIGTERM shuts down cleanly.',
    ],
    acceptanceCriteria: [
      'App can be started reproducibly.',
      'Healthcheck succeeds.',
      'SIGTERM shuts down cleanly.',
    ],
    dependencies: ['remediate.observability.health'],
  }),
  'docker.presence': entry({
    taskId: 'remediate.docker.presence',
    title: 'Add Docker packaging for repeatable runs',
    category: 'deployment',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Container packaging makes local and CI execution reproducible and reduces implicit environment drift.',
    recommendedApproach: ['Add a Dockerfile.', 'Add Compose if the app needs supporting services.', 'Keep runtime and health behavior deterministic.'].join('\n'),
    likelyFiles: ['Dockerfile', 'docker-compose.yml', 'package.json', 'src/index.ts'],
    suggestedTests: [
      'Container build succeeds.',
      'Runtime starts and exposes a healthcheck.',
    ],
    acceptanceCriteria: [
      'Container build succeeds.',
      'Runtime starts and exposes a healthcheck.',
    ],
    dependencies: ['remediate.deployment.readiness'],
  }),
  'env.example': entry({
    taskId: 'remediate.env.example',
    title: 'Document required environment variables in .env.example',
    category: 'env',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'A safe example environment file is the simplest way to document required secrets and configuration shape.',
    recommendedApproach: [
      'Add or refresh .env.example with safe placeholders only.',
      'Keep secret values out of the example file.',
      'Document the required runtime variables alongside the template.',
    ].join('\n'),
    likelyFiles: ['.env.example', 'backend/config/*', 'src/env.ts', 'src/config/*'],
    suggestedTests: [
      '.env.example contains placeholders only.',
      'Required env variables are documented.',
    ],
    acceptanceCriteria: [
      '.env.example documents required keys without real values.',
      'Secrets remain absent from the example file.',
    ],
    dependencies: [],
  }),
  'expectation.auth.required': entry({
    ...entry({
      taskId: 'remediate.auth.core',
      title: 'Implement an explicit authentication baseline',
      category: 'auth',
      phaseId: critical,
      priority: 'p0',
      effort: 'medium',
      risk: 'medium',
      automationReadiness: 'needs_review',
      why: 'A clear auth baseline is the prerequisite for protected resources, rate limits, tenant scoping, and privacy workflows.',
      recommendedApproach: [
        'Add a clear auth flow and secure credential handling.',
        'Ensure auth state is backed by explicit middleware or framework primitives.',
        'Cover login, logout, and session handling with tests.',
      ].join('\n'),
      likelyFiles: ['backend/routes/auth*', 'backend/middleware/auth*', 'src/auth*', 'src/middleware/*'],
      suggestedTests: [
        'Authenticated requests succeed and anonymous requests fail.',
        'Login/session setup is covered by tests.',
      ],
      acceptanceCriteria: [
        'Authentication flow is explicit and test-covered.',
        'Credentials and sessions are handled securely.',
      ],
      dependencies: [],
    }),
  }),
  'expectation.authz.resource-level.required': entry({
    ...entry({
      taskId: 'remediate.authz.resource-level',
      title: 'Add resource-level authorization checks',
      category: 'authz',
      phaseId: safety,
      priority: 'p1',
      effort: 'large',
      risk: 'high',
      automationReadiness: 'needs_review',
      why: 'Role-only authorization still allows IDOR-style access if resource ownership is not checked per object.',
      recommendedApproach: [
        'Introduce resource-level policy checks.',
        'Add ownership checks on read, update, and delete routes.',
        'Cover IDOR prevention with targeted tests.',
      ].join('\n'),
      likelyFiles: ['backend/routes/*', 'backend/services/*', 'src/routes/*', 'src/policies/*'],
      suggestedTests: [
        'Changing an ID in the URL cannot access another user\'s resource.',
        'Unauthorized update and delete return 403 or 404.',
      ],
      acceptanceCriteria: [
        'Changing an ID in the URL cannot access another user\'s resource.',
        'Unauthorized update and delete return 403 or 404.',
      ],
      dependencies: ['remediate.auth.core'],
    }),
  }),
  'expectation.tenancy.required': entry({
    ...entry({
      taskId: 'remediate.tenancy.b2b',
      title: 'Introduce explicit tenant and organization boundaries',
      category: 'tenancy',
      phaseId: safety,
      priority: 'p1',
      effort: 'large',
      risk: 'high',
      automationReadiness: 'manual_only',
      why: 'B2B signals without a tenant model create cross-tenant data leakage and authorization ambiguity.',
      recommendedApproach: [
        'Introduce Organization, Membership, and RoleAssignment models.',
        'Add tenant-context middleware.',
        'Scope queries by organizationId or tenantId.',
        'Add cross-tenant access tests.',
      ].join('\n'),
      likelyFiles: ['backend/models/*', 'backend/middleware/*', 'backend/routes/*', 'migrations/*', 'src/db/*'],
      suggestedTests: [
        'Tenant A cannot read, update, or delete Tenant B records.',
        'Tenant membership is explicit.',
        'Admin and owner roles are tenant-scoped.',
      ],
      acceptanceCriteria: [
        'User from tenant A cannot access tenant B records.',
        'Tenant membership is explicit.',
        'Admin and owner roles are tenant-scoped.',
      ],
      dependencies: ['remediate.auth.core'],
    }),
  }),
  'expectation.gdpr.required': entry({
    ...entry({
      taskId: 'remediate.gdpr.privacy',
      title: 'Add privacy and GDPR control flows',
      category: 'gdpr',
      phaseId: safety,
      priority: 'p1',
      effort: 'medium',
      risk: 'medium',
      automationReadiness: 'needs_review',
      why: 'If users exist, privacy workflows need explicit consent, export, erasure, and retention handling.',
      recommendedApproach: [
        'Add consent tracking.',
        'Add a data export endpoint.',
        'Add erasure request or delete-account flow.',
        'Add retention policy documentation or a retention job.',
      ].join('\n'),
      likelyFiles: ['backend/routes/privacy*', 'backend/routes/export*', 'backend/jobs/*', 'backend/models/*', 'src/privacy*'],
      suggestedTests: [
        'Authenticated user can request an export of personal data.',
        'Erasure request is tracked.',
        'Privacy event is audited.',
      ],
      acceptanceCriteria: [
        'Authenticated user can request export of personal data.',
        'Erasure request is tracked.',
        'Privacy event is audited.',
      ],
      dependencies: ['remediate.auth.core'],
    }),
  }),
  'expectation.billing.recommended': entry({
    ...entry({
      taskId: 'remediate.billing.baseline',
      title: 'Add billing and subscription baseline',
      category: 'billing',
      phaseId: safety,
      priority: 'p2',
      effort: 'medium',
      risk: 'medium',
      automationReadiness: 'needs_review',
      why: 'The product profile expects explicit billing or entitlement capabilities.',
      recommendedApproach: [
        'Define plan and subscription model.',
        'Integrate billing provider or entitlement service.',
        'Add webhook validation if Stripe is used.',
        'Add tests for subscription state and feature gating.',
      ].join('\n'),
      likelyFiles: ['backend/routes/billing*', 'backend/models/*', 'backend/services/*', '.env.example'],
      suggestedTests: [
        'Subscription state updates are persisted correctly.',
        'Feature gates respect plan and subscription status.',
        'Webhook events are validated before state changes.',
      ],
      acceptanceCriteria: [
        'Plan and subscription model is defined.',
        'Feature entitlement checks are enforced.',
        'Billing state changes are test-covered.',
      ],
      dependencies: [],
    }),
  }),
  'expectation.billing.required': entry({
    ...entry({
      taskId: 'remediate.billing.baseline',
      title: 'Add billing and subscription baseline',
      category: 'billing',
      phaseId: safety,
      priority: 'p1',
      effort: 'medium',
      risk: 'medium',
      automationReadiness: 'needs_review',
      why: 'The selected product profile requires explicit billing capability.',
      recommendedApproach: [
        'Define plan and subscription model.',
        'Integrate billing provider or entitlement service.',
        'Add webhook validation if Stripe is used.',
        'Add tests for subscription state and feature gating.',
      ].join('\n'),
      likelyFiles: ['backend/routes/billing*', 'backend/models/*', 'backend/services/*', '.env.example'],
      suggestedTests: [
        'Subscription state updates are persisted correctly.',
        'Feature gates respect plan and subscription status.',
        'Webhook events are validated before state changes.',
      ],
      acceptanceCriteria: [
        'Plan and subscription model is defined.',
        'Feature entitlement checks are enforced.',
        'Billing state changes are test-covered.',
      ],
      dependencies: [],
    }),
  }),
  'expectation.security.headers.required': entry({
    taskId: 'remediate.security.helmet',
    title: 'Add security headers middleware',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Helmet-style security headers are a low-risk baseline that improves browser-side hardening quickly.',
    recommendedApproach: ['Install and mount helmet before routes.', 'Tune CSP and HSTS for the deployment model.'].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/app.js', 'src/server.ts', 'src/app.ts'],
    suggestedTests: [
      'Helmet is mounted before routes.',
      'Production responses include security headers.',
    ],
    acceptanceCriteria: [
      'Helmet is mounted before routes.',
      'Production security headers are present.',
    ],
    dependencies: [],
  }),
  'expectation.security.cors.required': entry({
    taskId: 'remediate.security.cors-origin',
    title: 'Lock CORS to explicit allowed origins',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'safe_template',
    why: 'Permissive CORS can expose authenticated browser flows to unwanted cross-origin access.',
    recommendedApproach: [
      'Replace cors() defaults with an explicit allowlist.',
      'Drive allowed origins from environment variables.',
      'Reject unknown origins in production.',
    ].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/config/*', 'src/server.ts', '.env.example'],
    suggestedTests: [
      'Production CORS is not wildcard or permissive.',
      'Allowed origins are sourced from configuration.',
      'Unexpected origins are rejected.',
    ],
    acceptanceCriteria: [
      'Production CORS is not wildcard/permissive.',
      'Allowed origins are documented in .env.example.',
    ],
    dependencies: ['remediate.env.example'],
  }),
  'expectation.security.rate-limit.required': entry({
    taskId: 'remediate.security.rate-limit-auth',
    title: 'Rate limit authentication surfaces',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Login and password-reset endpoints are common brute-force targets and should be throttled explicitly.',
    recommendedApproach: [
      'Apply auth-specific rate limiting to login, register, and password-reset routes.',
      'Avoid throttling unrelated API traffic.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/middleware/*', 'src/routes/auth*', 'src/middleware/*'],
    suggestedTests: [
      'Repeated login attempts are throttled.',
      'Normal API routes are not unintentionally blocked.',
    ],
    acceptanceCriteria: [
      'Repeated login attempts are throttled.',
      'Normal API routes remain usable.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'expectation.uploads.required': entry({
    taskId: 'remediate.uploads.public-exposure',
    title: 'Protect public upload routes',
    category: 'uploads',
    phaseId: critical,
    priority: 'p0',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'needs_review',
    why: 'Anonymous upload exposure can lead to data leakage, abuse, and content-type bypasses.',
    recommendedApproach: [
      'Protect the /uploads static route with auth middleware.',
      'Validate MIME type and extension.',
      'Enforce maximum upload size.',
      'Prefer private object storage or signed URLs over public disk exposure.',
    ].join('\n'),
    likelyFiles: ['backend/app.js', 'backend/server.js', 'backend/routes/uploads*', 'backend/middleware/auth*'],
    suggestedTests: [
      'Anonymous access to protected uploads is denied.',
      'Oversized or invalid MIME uploads are rejected.',
      'Authenticated upload flow still works.',
    ],
    acceptanceCriteria: [
      'Uploads are not publicly exposed without auth checks.',
      'Anonymous access is denied for protected uploads.',
      'Upload validation rejects invalid files.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'expectation.observability.health.required': entry({
    taskId: 'remediate.observability.health',
    title: 'Add a runtime healthcheck endpoint',
    category: 'observability',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Health endpoints are a low-risk operational baseline for orchestration and deployment checks.',
    recommendedApproach: ['Add /health or /healthz and keep the response lightweight and deterministic.'].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/app.js', 'src/server.ts', 'src/app.ts'],
    suggestedTests: [
      'Health endpoint returns 200 in a healthy runtime.',
      'Health response stays deterministic and lightweight.',
    ],
    acceptanceCriteria: [
      'Healthcheck succeeds.',
      'Health endpoint is deterministic and lightweight.',
    ],
    dependencies: [],
  }),
  'expectation.observability.logging.recommended': entry({
    taskId: 'remediate.observability.logging',
    title: 'Add structured logging and request correlation',
    category: 'observability',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Structured logs and correlation ids make runtime troubleshooting and incident triage materially easier.',
    recommendedApproach: ['Add a structured logger.', 'Add request id or correlation id handling.', 'Centralize error logging.'].join('\n'),
    likelyFiles: ['backend/logger*', 'backend/middleware/*', 'src/logger*', 'src/middleware/*'],
    suggestedTests: [
      'Every request gets a request id.',
      'Server errors are logged with structured metadata.',
    ],
    acceptanceCriteria: [
      'Every request has a request id.',
      'Server errors are logged with structured metadata.',
    ],
    dependencies: [],
  }),
  'expectation.observability.logging.required': entry({
    taskId: 'remediate.observability.logging',
    title: 'Add structured logging and request correlation',
    category: 'observability',
    phaseId: ops,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Structured logs and correlation ids make runtime troubleshooting and incident triage materially easier.',
    recommendedApproach: ['Add a structured logger.', 'Add request id or correlation id handling.', 'Centralize error logging.'].join('\n'),
    likelyFiles: ['backend/logger*', 'backend/middleware/*', 'src/logger*', 'src/middleware/*'],
    suggestedTests: [
      'Every request gets a request id.',
      'Server errors are logged with structured metadata.',
    ],
    acceptanceCriteria: [
      'Every request has a request id.',
      'Server errors are logged with structured metadata.',
    ],
    dependencies: [],
  }),
  'expectation.deployment.required': entry({
    taskId: 'remediate.deployment.readiness',
    title: 'Add reproducible deployment assets',
    category: 'deployment',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'A reproducible deploy path reduces environment drift and makes operational behavior easier to verify.',
    recommendedApproach: [
      'Add a Dockerfile.',
      'Add docker-compose for local reproducibility when useful.',
      'Add healthcheck and graceful shutdown handling.',
      'Add production env validation.',
    ].join('\n'),
    likelyFiles: ['Dockerfile', 'docker-compose.yml', 'package.json', 'src/index.ts', 'backend/server.js'],
    suggestedTests: [
      'App can be started reproducibly.',
      'Healthcheck succeeds.',
      'SIGTERM shuts down cleanly.',
    ],
    acceptanceCriteria: [
      'App can be started reproducibly.',
      'Healthcheck succeeds.',
      'SIGTERM shuts down cleanly.',
    ],
    dependencies: ['remediate.observability.health'],
  }),
  'expectation.docker.recommended': entry({
    taskId: 'remediate.docker.presence',
    title: 'Add Docker packaging for repeatable runs',
    category: 'deployment',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Container packaging makes local and CI execution reproducible and reduces implicit environment drift.',
    recommendedApproach: ['Add a Dockerfile.', 'Add Compose if the app needs supporting services.', 'Keep runtime and health behavior deterministic.'].join('\n'),
    likelyFiles: ['Dockerfile', 'docker-compose.yml', 'package.json', 'src/index.ts'],
    suggestedTests: [
      'Container build succeeds.',
      'Runtime starts and exposes a healthcheck.',
    ],
    acceptanceCriteria: [
      'Container build succeeds.',
      'Runtime starts and exposes a healthcheck.',
    ],
    dependencies: ['remediate.deployment.readiness'],
  }),
  'expectation.audit.recommended': entry({
    taskId: 'remediate.audit.baseline',
    title: 'Add audit logging for sensitive actions',
    category: 'audit',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Sensitive actions should be traceable for compliance, support, and incident response.',
    recommendedApproach: [
      'Log auth, billing, admin, privacy, and destructive actions.',
      'Capture actor, action, target, timestamp, and request id.',
      'Avoid storing sensitive payload data in audit events.',
    ].join('\n'),
    likelyFiles: ['backend/middleware/*', 'backend/services/*', 'backend/routes/*', 'src/middleware/*'],
    suggestedTests: [
      'Sensitive actions generate audit entries.',
      'Audit entries include actor/action/target/request id/timestamp.',
      'Sensitive payloads are not persisted in audit logs.',
    ],
    acceptanceCriteria: [
      'Sensitive actions are auditable.',
      'Audit entries contain required context fields.',
      'Sensitive payloads are excluded from audit logs.',
    ],
    dependencies: [],
  }),

  // --- Capabilities split out of the former coarse expectations -------------
  // `expectation.tenancy.required`, `expectation.gdpr.required` and
  // `expectation.authz.resource-level.required` no longer exist: each is now a
  // granular capability with its own finding id, so each needs its own task.

  'expectation.tenancy.organization.required': entry({
    taskId: 'remediate.tenancy.organization',
    title: 'Introduce an explicit organization model',
    category: 'tenancy',
    phaseId: safety,
    priority: 'p0',
    effort: 'large',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'Without an organization entity that owns data, every record belongs to the whole system and there is nothing to scope access by.',
    recommendedApproach: [
      'Introduce an Organization (or Workspace) model as the owner of domain records.',
      'Add organizationId to every tenant-owned table with a migration.',
      'Resolve the active organization in request context.',
    ].join('\n'),
    likelyFiles: ['backend/models/*', 'backend/middleware/*', 'migrations/*', 'src/db/*'],
    suggestedTests: [
      'Domain records carry an organization reference.',
      'Request context resolves the active organization.',
    ],
    acceptanceCriteria: [
      'An organization entity exists and owns domain records.',
      'Every tenant-owned table references the organization.',
    ],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.tenancy.isolation.required': entry({
    taskId: 'remediate.tenancy.isolation',
    title: 'Enforce tenant isolation on every query',
    category: 'tenancy',
    phaseId: safety,
    priority: 'p0',
    effort: 'large',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'An organization model without enforced scoping still leaks: one tenant can read another tenant rows by guessing identifiers.',
    recommendedApproach: [
      'Model Membership explicitly and check it on access.',
      'Scope every query by the active tenant rather than filtering in application code.',
      'Add cross-tenant access tests as a regression guard.',
    ].join('\n'),
    likelyFiles: ['backend/middleware/*', 'backend/routes/*', 'backend/services/*', 'src/db/*'],
    suggestedTests: [
      'A user of tenant A cannot read, update or delete a record of tenant B.',
      'Membership is required to access organization data.',
    ],
    acceptanceCriteria: [
      'Cross-tenant access is rejected and covered by tests.',
      'Tenant membership is explicit.',
    ],
    dependencies: ['remediate.tenancy.organization'],
  }),

  'expectation.authz.roles.required': entry({
    taskId: 'remediate.authz.roles',
    title: 'Introduce a role or permission model',
    category: 'authz',
    phaseId: safety,
    priority: 'p0',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'Without roles, every authenticated user can perform every action, including administrative and destructive ones.',
    recommendedApproach: [
      'Define roles (or permissions) and assign them to users within their tenant.',
      'Check the role on privileged and destructive actions.',
    ].join('\n'),
    likelyFiles: ['backend/models/*', 'backend/middleware/*', 'backend/routes/*'],
    suggestedTests: [
      'A member role cannot perform owner-only actions.',
      'Role checks are enforced server-side.',
    ],
    acceptanceCriteria: [
      'Distinct roles exist and are enforced on privileged actions.',
    ],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.authz.ownership.required': entry({
    taskId: 'remediate.authz.ownership',
    title: 'Add per-record ownership checks',
    category: 'authz',
    phaseId: safety,
    priority: 'p0',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'Route-level authentication without record-level checks allows a valid user to act on another user records by changing an identifier.',
    recommendedApproach: [
      'Check ownership or membership for the specific record on read, update and delete.',
      'Prefer scoped queries over post-hoc comparison.',
    ].join('\n'),
    likelyFiles: ['backend/routes/*', 'backend/services/*', 'backend/policies/*'],
    suggestedTests: [
      'Requesting another user record by id returns 403 or 404.',
    ],
    acceptanceCriteria: [
      'Read, update and delete verify the caller may act on that specific record.',
    ],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.gdpr.consent.required': entry({
    taskId: 'remediate.gdpr.consent',
    title: 'Capture and store consent',
    category: 'gdpr',
    phaseId: safety,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Processing personal data needs a recorded lawful basis, and consent that is not stored cannot be demonstrated later.',
    recommendedApproach: [
      'Record consent with timestamp, subject and the version of the terms accepted.',
      'Expose the current consent state to the user.',
    ].join('\n'),
    likelyFiles: ['backend/models/*', 'backend/routes/privacy*', 'src/privacy*'],
    suggestedTests: ['Consent is persisted with timestamp and terms version.'],
    acceptanceCriteria: ['Consent is recorded and retrievable per user.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.gdpr.export.required': entry({
    taskId: 'remediate.gdpr.export',
    title: 'Add a personal data export endpoint',
    category: 'gdpr',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'GDPR article 20 gives users the right to obtain their personal data in a machine-readable form.',
    recommendedApproach: [
      'Add an authenticated export endpoint that gathers user data across stores.',
      'Produce a machine-readable archive and audit the request.',
    ].join('\n'),
    likelyFiles: ['backend/routes/export*', 'backend/services/*', 'backend/jobs/*'],
    suggestedTests: ['An authenticated user can export their own data and only their own.'],
    acceptanceCriteria: ['Export returns the user personal data in a machine-readable format.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.gdpr.erasure.required': entry({
    taskId: 'remediate.gdpr.erasure',
    title: 'Add an account erasure flow',
    category: 'gdpr',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'GDPR article 17 requires deletion of personal data on request, across every store that holds it.',
    recommendedApproach: [
      'Add a delete-account flow that removes or anonymises personal data.',
      'Cover derived stores: caches, search indexes, backups policy, logs.',
      'Audit the erasure request and its completion.',
    ].join('\n'),
    likelyFiles: ['backend/routes/privacy*', 'backend/services/*', 'backend/jobs/*'],
    suggestedTests: ['Erasure removes or anonymises the user across primary and derived stores.'],
    acceptanceCriteria: ['An erasure request is tracked and demonstrably completed.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.gdpr.retention.recommended': entry({
    taskId: 'remediate.gdpr.retention',
    title: 'Define and enforce retention limits',
    category: 'gdpr',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'needs_review',
    why: 'Personal data kept indefinitely by default increases breach impact and weakens the lawful basis for processing.',
    recommendedApproach: [
      'Define a retention window per data category.',
      'Run a scheduled job that deletes or anonymises data past its window.',
    ].join('\n'),
    likelyFiles: ['backend/jobs/*', 'backend/config/*'],
    suggestedTests: ['Data past its retention window is removed by the job.'],
    acceptanceCriteria: ['Retention windows are defined and enforced by a job.'],
    dependencies: [],
  }),

  'expectation.auth.password-reset.required': entry({
    taskId: 'remediate.auth.password-reset',
    title: 'Add a password reset flow',
    category: 'auth',
    phaseId: safety,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Without self-service recovery every locked-out user becomes a support request, and ad-hoc manual resets become their own attack surface.',
    recommendedApproach: [
      'Issue a single-use, expiring reset token delivered out of band.',
      'Invalidate active sessions on a successful reset.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/services/auth*'],
    suggestedTests: [
      'A reset token works once and expires.',
      'Sessions are invalidated after a reset.',
    ],
    acceptanceCriteria: ['Users can recover access without operator intervention.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.auth.email-verification.required': entry({
    taskId: 'remediate.auth.email-verification',
    title: 'Verify email ownership at signup',
    category: 'auth',
    phaseId: safety,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Unverified addresses allow impersonation of an address the signup does not control, and make abuse cheap.',
    recommendedApproach: [
      'Send a verification token and gate full account capabilities until it is used.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/services/auth*'],
    suggestedTests: ['An unverified account cannot use gated capabilities.'],
    acceptanceCriteria: ['Email ownership is proven before full access is granted.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.auth.mfa.required': entry({
    taskId: 'remediate.auth.mfa',
    title: 'Offer a second authentication factor',
    category: 'auth',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Accounts that move money or administer other users are worth stealing, and a password alone is a single point of failure.',
    recommendedApproach: [
      'Support TOTP or WebAuthn as a second factor.',
      'Require it at least for owner and admin roles.',
      'Provide recovery codes and audit their use.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/services/auth*', 'backend/models/*'],
    suggestedTests: [
      'An account with MFA enabled requires the second factor.',
      'Recovery codes work once.',
    ],
    acceptanceCriteria: ['A second factor is available and enforceable for privileged roles.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.billing.model.required': entry({
    taskId: 'remediate.billing.model',
    title: 'Introduce a billing and entitlement model',
    category: 'billing',
    phaseId: safety,
    priority: 'p1',
    effort: 'large',
    risk: 'medium',
    automationReadiness: 'manual_only',
    why: 'A product that charges needs plans and server-side entitlement checks, otherwise paid features are only hidden, not protected.',
    recommendedApproach: [
      'Model plans and subscriptions.',
      'Check entitlement server-side on every paid capability.',
    ].join('\n'),
    likelyFiles: ['backend/models/*', 'backend/services/billing*', 'backend/routes/*'],
    suggestedTests: ['A free-plan account cannot reach a paid capability by calling the API directly.'],
    acceptanceCriteria: ['Entitlement is enforced server-side, not only in the UI.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.billing.webhook-integrity.required': entry({
    taskId: 'remediate.billing.webhook-integrity',
    title: 'Verify payment webhook signatures',
    category: 'billing',
    phaseId: critical,
    priority: 'p0',
    effort: 'small',
    risk: 'high',
    automationReadiness: 'safe_template',
    why: 'An unverified payment webhook lets anyone forge a request that grants a paid plan for free, or marks an unpaid order as paid.',
    recommendedApproach: [
      'Verify the provider signature against the raw, unparsed request body.',
      'Load the signing secret from configuration with no fallback default.',
      'Reject and log requests that fail verification.',
    ].join('\n'),
    likelyFiles: ['backend/routes/webhook*', 'backend/routes/stripe*', 'src/app/api/webhook*'],
    suggestedTests: [
      'A request with an invalid signature is rejected.',
      'The raw body is used for verification, not the parsed one.',
    ],
    acceptanceCriteria: ['Only signature-verified webhook events change billing state.'],
    dependencies: [],
  }),
};

/**
 * Expectation findings carry their importance in the id
 * (`expectation.auth.mfa.required` vs `...recommended`), but the remediation work is
 * the same either way — only the urgency differs, and that is already carried by the
 * finding severity. Falling back across the importance suffix avoids duplicating every
 * catalogue entry once per profile that grades the capability differently.
 */
const IMPORTANCE_SUFFIXES = ['.required', '.recommended'] as const;

export function getRemediationEntry(findingId: string): RemediationCatalogEntry | undefined {
  const exact = remediationCatalog[findingId];
  if (exact) return exact;

  for (const suffix of IMPORTANCE_SUFFIXES) {
    if (!findingId.endsWith(suffix)) continue;

    const stem = findingId.slice(0, -suffix.length);
    for (const alternative of IMPORTANCE_SUFFIXES) {
      if (alternative === suffix) continue;

      const candidate = remediationCatalog[`${stem}${alternative}`];
      if (candidate) return candidate;
    }
  }

  return undefined;
}
