import type { RemediationCatalogEntry, RemediationPhaseId } from './types';

function entry(overrides: RemediationCatalogEntry): RemediationCatalogEntry {
  return overrides;
}

const critical: RemediationPhaseId = 'critical-blockers';
const safety: RemediationPhaseId = 'saas-safety-layer';
const ops: RemediationPhaseId = 'operational-readiness';

export const remediationCatalog: Record<string, RemediationCatalogEntry> = {
  'security.weak-secret': entry({
    taskId: 'remediate.security.weak-secret',
    title: 'Remove fallback secrets and enforce startup validation',
    category: 'security',
    phaseId: critical,
    priority: 'p0',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'safe_template',
    why: 'Fallback secrets allow production to boot with insecure defaults and can silently weaken signing or session protection.',
    recommendedApproach: [
      'Remove fallback values for JWT_SECRET, SESSION_SECRET, SECRET_KEY, and similar signing material.',
      'Fail fast during startup when required secrets are missing in production.',
      'Update .env.example with safe placeholders only.',
      'Add tests for missing-secret startup failure and placeholder-only examples.',
    ].join('\n'),
    likelyFiles: ['.env.example', 'backend/server.js', 'backend/config/*', 'src/server.ts'],
    suggestedTests: [
      'Startup fails when required secret env vars are missing.',
      '.env.example contains placeholders only.',
      'No config path falls back to a hardcoded signing secret.',
    ],
    acceptanceCriteria: [
      'No weak fallback secret remains.',
      'App fails on production startup if a required secret is missing.',
      '.env.example documents required secret keys without real values.',
    ],
    dependencies: ['remediate.env.example'],
  }),
  /**
   * Two Django checks and five capability families reached the report without ever
   * reaching the plan.
   *
   * 164 of 885 open findings across the verification corpus had no task behind them —
   * nineteen per cent of everything the reports told somebody to fix. Two of them were
   * criticals: a Django project running with DEBUG on was told to stop and given no
   * step to take.
   */
  /**
   * The packaging capabilities arrived with the `library` profile in 0.10.0 and their
   * tasks did not, so a package was told its licence was missing and handed no step.
   */
  /**
   * The mobile and consumer families, which arrived with their profiles and without
   * their tasks.
   */
  'expectation.mobile.permissions.required': entry({
    taskId: 'remediate.mobile.permissions',
    title: 'Ask for a permission where the person can see why',
    category: 'mobile',
    phaseId: safety,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'needs_review',
    why: 'A permission declared with nothing next to it is a prompt the person meets cold, and a refusal you never recover from \u2014 on both stores a declaration also has to be justified in the listing.',
    recommendedApproach: [
      'Declare only the permissions something in the product actually uses.',
      'Ask at the moment the feature needs it, not at launch.',
      'Handle the refusal: the feature degrades, the application does not stop.',
    ].join('\n'),
    likelyFiles: ['ios/Runner/Info.plist', 'android/app/src/main/AndroidManifest.xml', 'lib/**/permission*'],
    suggestedTests: ['Every declared permission is requested by some code path.', 'A refused permission leaves the app usable.'],
    acceptanceCriteria: ['No permission is declared that nothing uses, and a refusal is handled.'],
    dependencies: [],
  }),
  'expectation.mobile.credential-storage.required': entry({
    taskId: 'remediate.mobile.credential-storage',
    title: 'Put credentials in the keystore, not in a file',
    category: 'mobile',
    phaseId: safety,
    priority: 'p0',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'On a phone the file system is not a security boundary: preferences and plain files are readable on a rooted or jailbroken device and often survive into a backup.',
    recommendedApproach: [
      'Store tokens in the Keychain or the Android Keystore through the platform API.',
      'Keep nothing long-lived in shared preferences or a plain file.',
      'Clear credentials on sign-out and on an account switch.',
    ].join('\n'),
    likelyFiles: ['lib/**/auth*', 'lib/**/storage*', 'android/app/src/main/*', 'ios/Runner/*'],
    suggestedTests: ['A stored token is not readable from plain application storage.', 'Sign-out removes the credential.'],
    acceptanceCriteria: ['Credentials live in platform secure storage and are cleared on sign-out.'],
    dependencies: [],
  }),
  'expectation.mobile.offline.required': entry({
    taskId: 'remediate.mobile.offline',
    title: 'Behave when the network is not there',
    category: 'mobile',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'A network that comes and goes is the normal state of a phone, not an error case: an application that only works on a good connection is one that fails on a train.',
    recommendedApproach: [
      'Cache what the person last saw, so a cold screen is not empty.',
      'Queue writes made offline and reconcile them when the connection returns.',
      'Say which state is showing: stale, syncing, or live.',
    ].join('\n'),
    likelyFiles: ['lib/**/repository*', 'lib/**/cache*', 'lib/**/sync*'],
    suggestedTests: ['A screen renders from cache with the network off.', 'A write made offline arrives once the connection returns.'],
    acceptanceCriteria: ['The application is usable offline and does not lose a write made there.'],
    dependencies: [],
  }),
  'expectation.mobile.forced-update.recommended': entry({
    taskId: 'remediate.mobile.forced-update',
    title: 'Be able to require a newer version',
    category: 'mobile',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'A web application changes for everyone at once. A phone application does not: old versions keep calling your API for as long as somebody declines to update, and a breaking change reaches them as a crash.',
    recommendedApproach: [
      'Send a minimum supported version from the server and check it at launch.',
      'Show a blocking screen with a link to the store when the build is below it.',
      'Keep the check cheap so it does not delay a cold start.',
    ].join('\n'),
    likelyFiles: ['lib/main.dart', 'lib/**/version*', 'src/App.*'],
    suggestedTests: ['A build below the minimum shows the update screen.', 'The check does not block start when the server is unreachable.'],
    acceptanceCriteria: ['The server can require a newer build, and an old one is told rather than broken.'],
    dependencies: [],
  }),
  'expectation.mobile.privacy-declaration.recommended': entry({
    taskId: 'remediate.mobile.privacy-declaration',
    title: 'Make the store listing match what the code collects',
    category: 'mobile',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'needs_review',
    why: 'The App Store and Play listings are a public, checkable claim about what the product collects. A declaration that does not match the SDKs in the build is the kind of discrepancy a reviewer finds.',
    recommendedApproach: [
      'List what is collected, by the application and by every SDK it embeds.',
      'Fill in the store privacy form from that list, not from memory.',
      'Revisit it when a dependency is added.',
    ].join('\n'),
    likelyFiles: ['ios/Runner/PrivacyInfo.xcprivacy', 'android/app/src/main/AndroidManifest.xml', 'pubspec.yaml'],
    suggestedTests: ['Every data type an SDK collects appears in the declaration.'],
    acceptanceCriteria: ['The store declaration matches what the build actually collects.'],
    dependencies: [],
  }),
  'expectation.b2c.notifications.required': entry({
    taskId: 'remediate.b2c.notifications',
    title: 'Be able to reach the person after they leave',
    category: 'auth',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'low',
    automationReadiness: 'needs_review',
    why: 'A consumer product that cannot send a confirmation, a reset or a receipt has no way to recover an account or to prove that something happened.',
    recommendedApproach: [
      'Wire a transactional provider and cover the account lifecycle: verification, reset, and the receipt for anything paid.',
      'Send from a domain you control, with SPF and DKIM set, or the mail goes to spam.',
      'Log what was sent, so a dispute can be answered.',
    ].join('\n'),
    likelyFiles: ['src/lib/mail*', 'src/services/*mail*', 'templates/email/*'],
    suggestedTests: ['A password reset produces a message.', 'Sending failure is logged rather than swallowed.'],
    acceptanceCriteria: ['Every account lifecycle event the product needs can reach the person.'],
    dependencies: [],
  }),
  'expectation.b2c.onboarding.required': entry({
    taskId: 'remediate.b2c.onboarding',
    title: 'Make the first run lead somewhere',
    category: 'client',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'low',
    automationReadiness: 'needs_review',
    why: 'A consumer product is judged in its first minute by somebody who owes it nothing. An empty screen with no next step is where most of them stop.',
    recommendedApproach: [
      'Give the empty state one obvious action rather than a blank list.',
      'Carry the person to a first result, with sample data if that is what it takes.',
      'Measure where they stop, so the guess can be checked.',
    ].join('\n'),
    likelyFiles: ['src/app/**/page.tsx', 'src/components/**/Empty*'],
    suggestedTests: ['Every list has an empty state with an action.'],
    acceptanceCriteria: ['A new account reaches a first result without being told how.'],
    dependencies: [],
  }),
  'expectation.auth.api-keys.required': entry({
    taskId: 'remediate.auth.api-keys',
    title: 'Issue API keys you can identify and revoke',
    category: 'auth',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'A key that cannot be revoked without changing everybody else\u2019s is a key that never gets revoked, and one stored as it arrived is a breach that reads itself.',
    recommendedApproach: [
      'Store a hash of the key, never the key, and show the value once at creation.',
      'Give each key an owner, a scope and a last-used timestamp.',
      'Allow revocation of one key without disturbing the rest.',
    ].join('\n'),
    likelyFiles: ['src/lib/auth/*', 'src/models/*key*', 'prisma/schema.prisma'],
    suggestedTests: ['A revoked key is refused.', 'The stored value cannot be used to authenticate.'],
    acceptanceCriteria: ['Keys are hashed at rest, scoped, and individually revocable.'],
    dependencies: [],
  }),
  'expectation.ai.prompt-safety.required': entry({
    taskId: 'remediate.ai.prompt-safety',
    title: 'Treat what the model reads as untrusted',
    category: 'security',
    phaseId: critical,
    priority: 'p0',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'needs_review',
    why: 'Anything the model reads \u2014 a document, a web page, a user message \u2014 can contain instructions, and a model that acts on tools cannot tell them from yours.',
    recommendedApproach: [
      'Keep retrieved content out of the instruction position: it is data the model is reading, not a command.',
      'Gate every side-effectful tool behind a check the model cannot talk its way past.',
      'Log the prompt and the tool calls, so an incident can be reconstructed.',
    ].join('\n'),
    likelyFiles: ['src/lib/ai/*', 'src/services/*ai*', 'src/agents/*'],
    suggestedTests: ['Injected instructions in retrieved content do not trigger a tool call.', 'A destructive tool requires an out-of-band confirmation.'],
    acceptanceCriteria: ['Retrieved content cannot cause a side effect on its own.'],
    dependencies: [],
  }),
  'expectation.ai.cost-control.required': entry({
    taskId: 'remediate.ai.cost-control',
    title: 'Put a ceiling on what a request can spend',
    category: 'security',
    phaseId: safety,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'A model call is the one endpoint where a loop or an abusive caller turns directly into an invoice, and the bill arrives a month after the traffic.',
    recommendedApproach: [
      'Cap max tokens per request and requests per caller.',
      'Track spend per account, so an anomaly is visible before the invoice.',
      'Fail closed when a budget is exceeded, rather than continuing quietly.',
    ].join('\n'),
    likelyFiles: ['src/lib/ai/*', 'src/middleware*'],
    suggestedTests: ['A caller cannot exceed the per-account budget.', 'Token limits are set on every model call.'],
    acceptanceCriteria: ['No single caller can run the bill up without hitting a limit.'],
    dependencies: [],
  }),
  'expectation.jobs.recommended': entry({
    taskId: 'remediate.jobs.background',
    title: 'Move slow work out of the request',
    category: 'jobs',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Slow work inside the request makes the person wait for something they did not ask to watch, and a failure halfway through cannot be retried.',
    recommendedApproach: [
      'Move the slow part to a queue and return immediately with something to poll or subscribe to.',
      'Make the job idempotent, so a retry is safe.',
      'Record failures where somebody will see them.',
    ].join('\n'),
    likelyFiles: ['src/workers/*', 'src/jobs/*', 'docker-compose.yml'],
    suggestedTests: ['A queued job that fails is retried without duplicating its effect.'],
    acceptanceCriteria: ['Nothing slow runs inside the request path, and failures are retryable.'],
    dependencies: [],
  }),
  'expectation.packaging.metadata.required': entry({
    taskId: 'remediate.packaging.metadata',
    title: 'Say what the package is, in the manifest',
    category: 'deployment',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'A name and a version are what anything else has to write down in order to depend on this. Without them the code can be copied but not installed, and never updated.',
    recommendedApproach: [
      'Set name, version, description and repository in the manifest.',
      'Follow semantic versioning, so a consumer can tell a patch from a break.',
      'Say which runtime versions are supported.',
    ].join('\n'),
    likelyFiles: ['package.json', 'pyproject.toml', 'composer.json'],
    suggestedTests: ['The manifest carries a name, a version and a repository.'],
    acceptanceCriteria: ['Another project can install this by name and know where it came from.'],
    dependencies: [],
  }),
  'expectation.packaging.entrypoints.required': entry({
    taskId: 'remediate.packaging.entrypoints',
    title: 'Say where the package starts',
    category: 'deployment',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'A consumer needs to be told where the package begins: main, module, exports or bin for Node, a console script or package declaration for Python. Types are the difference between a package a TypeScript consumer can use and one they have to describe by hand.',
    recommendedApproach: [
      'Declare the entry point the manifest is missing, and a bin for anything meant to be run.',
      'Ship type declarations next to it.',
      'Install the built package into an empty project and import it, which is the only check that counts.',
    ].join('\n'),
    likelyFiles: ['package.json', 'pyproject.toml', 'tsconfig.json'],
    suggestedTests: ['A fresh project can import the built package by name.'],
    acceptanceCriteria: ['The package resolves and imports from a clean install.'],
    dependencies: [],
  }),
  'expectation.docs.readme.required': entry({
    taskId: 'remediate.docs.readme',
    title: 'Write down what this is',
    category: 'deployment',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'needs_review',
    why: 'For a package the README is the interface: it is what a person reads before deciding to install, and usually the only documentation there will ever be.',
    recommendedApproach: [
      'Say what it does in the first two lines, before anything else.',
      'Show how to install it and one example that runs as written.',
      'State the supported versions and the licence.',
    ].join('\n'),
    likelyFiles: ['README.md'],
    suggestedTests: ['The example in the README runs as written.'],
    acceptanceCriteria: ['A stranger can decide whether to install it, and then install it.'],
    dependencies: [],
  }),
  'expectation.marketplace.multi-role.required': entry({
    taskId: 'remediate.marketplace.multi-role',
    title: 'Separate the two sides of the transaction',
    category: 'authz',
    phaseId: safety,
    priority: 'p0',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'needs_review',
    why: 'Supply and demand being the same kind of account means nothing restricts a seller from acting as a buyer, or either from acting as an administrator.',
    recommendedApproach: [
      'Give the account a role, and check it where the sides differ rather than in the interface.',
      'Keep seller-only actions behind a server-side check.',
      'Decide what happens when one person is both, and write it down.',
    ].join('\n'),
    likelyFiles: ['src/models/*', 'src/lib/auth/*', 'prisma/schema.prisma'],
    suggestedTests: ['A buyer cannot reach a seller-only action by calling the endpoint directly.'],
    acceptanceCriteria: ['The two sides are distinguishable and enforced on the server.'],
    dependencies: [],
  }),
  'expectation.marketplace.payout.required': entry({
    taskId: 'remediate.marketplace.payout',
    title: 'Be able to pay the other side',
    category: 'billing',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'needs_review',
    why: 'Money can be collected but not paid out, which is the half of a marketplace that makes it one \u2014 and the half with the regulatory weight.',
    recommendedApproach: [
      'Use the payment provider\u2019s connected-account flow rather than moving money yourself.',
      'Record every payout against the transactions it settles.',
      'Handle the failure path: a payout that bounces has to be visible and retryable.',
    ].join('\n'),
    likelyFiles: ['src/lib/billing/*', 'src/services/*payout*'],
    suggestedTests: ['A payout is traceable to the transactions it settles.', 'A failed payout is recorded rather than lost.'],
    acceptanceCriteria: ['The platform can pay sellers, and every payout reconciles.'],
    dependencies: [],
  }),
  'expectation.marketplace.commission.required': entry({
    taskId: 'remediate.marketplace.commission',
    title: 'Record the cut on every transaction',
    category: 'billing',
    phaseId: safety,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'A platform that takes no recorded cut cannot reconcile revenue per transaction, and cannot answer a seller asking what they were charged.',
    recommendedApproach: [
      'Store the fee alongside the transaction, not only in the provider.',
      'Use the provider\u2019s application fee so the split is atomic with the charge.',
      'Show the seller what was deducted.',
    ].join('\n'),
    likelyFiles: ['src/lib/billing/*', 'prisma/schema.prisma'],
    suggestedTests: ['Every transaction carries its fee.', 'The sum of fees reconciles with the provider.'],
    acceptanceCriteria: ['Revenue per transaction can be reconstructed from your own records.'],
    dependencies: [],
  }),
  'expectation.marketplace.dispute.required': entry({
    taskId: 'remediate.marketplace.dispute',
    title: 'Have a way to answer a dispute',
    category: 'audit',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'A dispute arrives with a deadline and is decided on evidence. Without a record of what was ordered, delivered and said, the platform loses by default.',
    recommendedApproach: [
      'Keep an immutable record of the order, the delivery and the messages around it.',
      'Handle the provider\u2019s dispute webhook rather than finding out by email.',
      'Give support a way to see the whole transaction in one place.',
    ].join('\n'),
    likelyFiles: ['src/lib/billing/*', 'src/models/*', 'src/app/api/webhooks/*'],
    suggestedTests: ['A dispute webhook is recorded and surfaced.', 'The full history of a transaction is retrievable.'],
    acceptanceCriteria: ['A dispute can be answered from records the platform already holds.'],
    dependencies: [],
  }),
  'expectation.packaging.license.required': entry({
    taskId: 'remediate.packaging.license',
    title: 'Give the package a licence somebody may rely on',
    category: 'deployment',
    phaseId: critical,
    priority: 'p0',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Code published without a licence is, by default, code nobody else may legally use. For a package that is not a missing file, it is the thing that stops it being a package.',
    recommendedApproach: [
      'Choose a licence and add the full text as a LICENSE file.',
      'Name the same licence in the package manifest, so tooling can read it.',
      'Check that bundled dependencies permit the licence you chose.',
    ].join('\n'),
    likelyFiles: ['LICENSE', 'package.json', 'pyproject.toml'],
    suggestedTests: ['The manifest names a licence and a LICENSE file exists.'],
    acceptanceCriteria: ['The licence is stated in both the file and the manifest, and they agree.'],
    dependencies: [],
  }),
  'expectation.quality.tests.required': entry({
    taskId: 'remediate.quality.tests',
    title: 'Give the package something that proves it works',
    category: 'deployment',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'low',
    automationReadiness: 'needs_review',
    why: 'A library is depended on by code its author will never see, so the only claim it can make about a release is the one its tests make. Test files with no way to run them are half of the answer.',
    recommendedApproach: [
      'Cover the public entry points first: what a consumer imports is what a consumer breaks on.',
      'Add a single command that runs them, so a contributor does not have to guess.',
      'Include the cases the README promises.',
    ].join('\n'),
    likelyFiles: ['tests/*', 'src/**/*.test.*', 'package.json', 'pyproject.toml'],
    suggestedTests: ['Every exported entry point is exercised at least once.'],
    acceptanceCriteria: ['One command runs the suite and it covers the public surface.'],
    dependencies: [],
  }),
  'expectation.quality.ci.recommended': entry({
    taskId: 'remediate.quality.ci',
    title: 'Run the tests without anybody remembering to',
    category: 'deployment',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Tests that only run when someone thinks to run them are tests that stop running. For a package published from a developer machine, continuous integration is what separates a release that was checked from one that compiled.',
    recommendedApproach: [
      'Run the suite on every push and every pull request.',
      'Run it on the versions the manifest says it supports, not only the one on your laptop.',
      'Make the release depend on it passing.',
    ].join('\n'),
    likelyFiles: ['.github/workflows/*', '.gitlab-ci.yml'],
    suggestedTests: ['A pull request with a failing test cannot be merged.'],
    acceptanceCriteria: ['The suite runs on every push, and a release cannot go out red.'],
    dependencies: ['remediate.quality.tests'],
  }),
  'security.django-debug': entry({
    taskId: 'remediate.security.django-debug',
    title: 'Turn DEBUG off outside development',
    category: 'security',
    phaseId: critical,
    priority: 'p0',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Django with DEBUG on serves a full traceback, the settings around it and the SQL it ran to anybody who triggers an error, and disables ALLOWED_HOSTS.',
    recommendedApproach: [
      'Read DEBUG from the environment and default it to False.',
      'Set ALLOWED_HOSTS from configuration, since DEBUG off makes it mandatory.',
      'Check the deployed settings module is the one you think it is.',
    ].join('\n'),
    likelyFiles: ['*/settings.py', '.env.example', 'docker-compose.yml'],
    suggestedTests: [
      'Settings raise or refuse to start when DEBUG is true and the environment is production.',
      'ALLOWED_HOSTS is non-empty when DEBUG is false.',
    ],
    acceptanceCriteria: [
      'DEBUG is False by default and only true when explicitly set.',
      'A production deployment cannot start with DEBUG on.',
    ],
    dependencies: ['remediate.env.example'],
  }),
  'security.django-secure-cookies': entry({
    taskId: 'remediate.security.django-secure-cookies',
    title: 'Mark session and CSRF cookies secure',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'A session cookie without the Secure flag is sent over plain HTTP, where anything between the user and the server can read it and become them.',
    recommendedApproach: [
      'Set SESSION_COOKIE_SECURE and CSRF_COOKIE_SECURE to True outside development.',
      'Set SESSION_COOKIE_HTTPONLY so scripts cannot read the session.',
      'Consider SESSION_COOKIE_SAMESITE to limit cross-site submission.',
    ].join('\n'),
    likelyFiles: ['*/settings.py'],
    suggestedTests: [
      'Session and CSRF cookies carry Secure outside development.',
      'The session cookie is HttpOnly.',
    ],
    acceptanceCriteria: ['Session and CSRF cookies are Secure and HttpOnly in production.'],
    dependencies: [],
  }),
  'expectation.client.error-reporting.required': entry({
    taskId: 'remediate.client.error-reporting',
    title: 'Report crashes from the device they happen on',
    category: 'observability',
    phaseId: ops,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'On a server a crash is in the logs whether anyone was watching or not. On somebody else\u2019s phone or browser it is a person deciding not to come back, and you never hear about it.',
    recommendedApproach: [
      'Add a crash and error reporter, and let it capture unhandled errors and rejections rather than only what you remember to send.',
      'Attach a release or build identifier so a spike can be traced to a deploy.',
      'Strip personal data from what is sent.',
    ].join('\n'),
    likelyFiles: ['src/main.*', 'src/App.*', 'lib/main.dart', 'sentry.client.config.*'],
    suggestedTests: [
      'An unhandled error reaches the reporter.',
      'Reports carry the release identifier.',
    ],
    acceptanceCriteria: ['Crashes on a user device are visible without the user reporting them.'],
    dependencies: [],
  }),
  'expectation.app.state-durability.required': entry({
    taskId: 'remediate.app.state-durability',
    title: 'Keep the user\u2019s work somewhere it survives',
    category: 'client',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Storage the platform is free to clear \u2014 a cache, a private window, a reinstall, a new device \u2014 loses the work without ever telling the person the save was not real.',
    recommendedApproach: [
      'Persist progress outside volatile storage: a server, a synced store, or the platform\u2019s durable storage.',
      'Treat the local copy as a cache of the record rather than as the record.',
      'Say what is saved and when, so an unsaved state is visible.',
    ].join('\n'),
    likelyFiles: ['src/store/*', 'src/state/*', 'lib/**/repository*'],
    suggestedTests: [
      'Progress survives clearing browser storage or reinstalling.',
      'An unsaved change is distinguishable from a saved one.',
    ],
    acceptanceCriteria: ['Nothing the person has done is lost by a cache clear.'],
    dependencies: [],
  }),
  'expectation.app.asset-delivery.required': entry({
    taskId: 'remediate.app.asset-delivery',
    title: 'Cache the assets the first screen waits for',
    category: 'client',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Sprites, audio and models are most of what a player downloads. Served without cache headers they are fetched again on every visit, which is the difference between a game that starts and one abandoned while it loads.',
    recommendedApproach: [
      'Serve static assets with long-lived cache headers and fingerprinted filenames.',
      'Put a CDN in front of them, or use the platform\u2019s asset pipeline.',
      'Compress what compresses and check the first-load size.',
    ].join('\n'),
    likelyFiles: ['public/*', 'assets/*', 'next.config.*', 'nginx.conf'],
    suggestedTests: [
      'Static assets respond with a long max-age and a fingerprinted name.',
      'A second visit does not refetch unchanged assets.',
    ],
    acceptanceCriteria: ['Repeat visits do not re-download unchanged assets.'],
    dependencies: [],
  }),
  'security.cors-origin': entry({
    taskId: 'remediate.security.cors-origin',
    title: 'Lock CORS to explicit allowed origins',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'safe_template',
    why: 'Permissive CORS can expose authenticated browser flows to unwanted cross-origin access.',
    recommendedApproach: [
      'Replace cors() defaults with an explicit allowlist.',
      'Drive allowed origins from environment variables.',
      'Reject unknown origins in production.',
    ].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/config/*', 'src/server.ts', '.env.example'],
    suggestedTests: [
      'Production CORS is not wildcard or permissive.',
      'Allowed origins are sourced from configuration.',
      'Unexpected origins are rejected.',
    ],
    acceptanceCriteria: [
      'Production CORS is not wildcard/permissive.',
      'Allowed origins are documented in .env.example.',
    ],
    dependencies: ['remediate.env.example'],
  }),
  'security.helmet': entry({
    taskId: 'remediate.security.helmet',
    title: 'Add security headers middleware',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Helmet-style security headers are a low-risk baseline that improves browser-side hardening quickly.',
    recommendedApproach: ['Install and mount helmet before routes.', 'Tune CSP and HSTS for the deployment model.'].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/app.js', 'src/server.ts', 'src/app.ts'],
    suggestedTests: [
      'Helmet is mounted before routes.',
      'Production responses include security headers.',
    ],
    acceptanceCriteria: [
      'Helmet is mounted before routes.',
      'Production security headers are present.',
    ],
    dependencies: [],
  }),
  'security.rate-limit-auth': entry({
    taskId: 'remediate.security.rate-limit-auth',
    title: 'Rate limit authentication surfaces',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Login and password-reset endpoints are common brute-force targets and should be throttled explicitly.',
    recommendedApproach: [
      'Apply auth-specific rate limiting to login, register, and password-reset routes.',
      'Avoid throttling unrelated API traffic.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/middleware/*', 'src/routes/auth*', 'src/middleware/*'],
    suggestedTests: [
      'Repeated login attempts are throttled.',
      'Normal API routes are not unintentionally blocked.',
    ],
    acceptanceCriteria: [
      'Repeated login attempts are throttled.',
      'Normal API routes remain usable.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'uploads.public-exposure': entry({
    taskId: 'remediate.uploads.public-exposure',
    title: 'Protect public upload routes',
    category: 'uploads',
    phaseId: critical,
    priority: 'p0',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'needs_review',
    why: 'Anonymous upload exposure can lead to data leakage, abuse, and content-type bypasses.',
    recommendedApproach: [
      'Protect the /uploads static route with auth middleware.',
      'Validate MIME type and extension.',
      'Enforce maximum upload size.',
      'Prefer private object storage or signed URLs over public disk exposure.',
    ].join('\n'),
    likelyFiles: ['backend/app.js', 'backend/server.js', 'backend/routes/uploads*', 'backend/middleware/auth*'],
    suggestedTests: [
      'Anonymous access to protected uploads is denied.',
      'Oversized or invalid MIME uploads are rejected.',
      'Authenticated upload flow still works.',
    ],
    acceptanceCriteria: [
      'Uploads are not publicly exposed without auth checks.',
      'Anonymous access is denied for protected uploads.',
      'Upload validation rejects invalid files.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'auth.core': entry({
    taskId: 'remediate.auth.core',
    title: 'Implement an explicit authentication baseline',
    category: 'auth',
    phaseId: critical,
    priority: 'p0',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'A clear auth baseline is the prerequisite for protected resources, rate limits, tenant scoping, and privacy workflows.',
    recommendedApproach: [
      'Add a clear auth flow and secure credential handling.',
      'Ensure auth state is backed by explicit middleware or framework primitives.',
      'Cover login, logout, and session handling with tests.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/middleware/auth*', 'src/auth*', 'src/middleware/*'],
    suggestedTests: [
      'Authenticated requests succeed and anonymous requests fail.',
      'Login/session setup is covered by tests.',
    ],
    acceptanceCriteria: [
      'Authentication flow is explicit and test-covered.',
      'Credentials and sessions are handled securely.',
    ],
    dependencies: [],
    supersededBy: ['expectation.auth.required', 'expectation.auth.password-reset.required', 'expectation.auth.email-verification.required', 'expectation.auth.mfa.required'],
  }),
  'billing.webhook-signature': entry({
    taskId: 'remediate.billing.webhook-signature',
    title: 'Harden Stripe webhook verification',
    category: 'billing',
    phaseId: critical,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Webhook processing without raw-body handling and signature checks can accept spoofed billing events.',
    recommendedApproach: [
      'Ensure the webhook route uses raw body handling before JSON parsing when required.',
      'Use STRIPE_WEBHOOK_SECRET from configuration.',
      'Validate stripe-signature with stripe.webhooks.constructEvent before processing events.',
      'Add tests for invalid and valid webhook signatures.',
    ].join('\n'),
    likelyFiles: ['backend/routes/webhook*', 'backend/server.js', 'backend/middleware/*', 'src/routes/*', '.env.example'],
    suggestedTests: [
      'Invalid Stripe signature returns 400.',
      'Valid Stripe event is accepted.',
      'Webhook parsing happens before JSON body parsing when required.',
    ],
    acceptanceCriteria: [
      'Invalid Stripe signature returns 400.',
      'Valid Stripe event is accepted.',
      'Webhook parsing uses the correct body mode for signature verification.',
    ],
    dependencies: ['remediate.env.example'],
  }),
  'tenancy.b2b': entry({
    taskId: 'remediate.tenancy.b2b',
    title: 'Introduce explicit tenant and organization boundaries',
    category: 'tenancy',
    phaseId: safety,
    priority: 'p1',
    effort: 'large',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'B2B signals without a tenant model create cross-tenant data leakage and authorization ambiguity.',
    recommendedApproach: [
      'Introduce Organization, Membership, and RoleAssignment models.',
      'Add tenant-context middleware.',
      'Scope queries by organizationId or tenantId.',
      'Add cross-tenant access tests.',
    ].join('\n'),
    likelyFiles: ['backend/models/*', 'backend/middleware/*', 'backend/routes/*', 'migrations/*', 'src/db/*'],
    suggestedTests: [
      'Tenant A cannot read, update, or delete Tenant B records.',
      'Tenant membership is explicit.',
      'Admin and owner roles are tenant-scoped.',
    ],
    acceptanceCriteria: [
      'User from tenant A cannot access tenant B records.',
      'Tenant membership is explicit.',
      'Admin and owner roles are tenant-scoped.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'authz.resource-level': entry({
    taskId: 'remediate.authz.resource-level',
    title: 'Add resource-level authorization checks',
    category: 'authz',
    phaseId: safety,
    priority: 'p1',
    effort: 'large',
    risk: 'high',
    automationReadiness: 'needs_review',
    why: 'Role-only authorization still allows IDOR-style access if resource ownership is not checked per object.',
    recommendedApproach: [
      'Introduce resource-level policy checks.',
      'Add ownership checks on read, update, and delete routes.',
      'Cover IDOR prevention with targeted tests.',
    ].join('\n'),
    likelyFiles: ['backend/routes/*', 'backend/services/*', 'src/routes/*', 'src/policies/*'],
    suggestedTests: [
      'Changing an ID in the URL cannot access another user\'s resource.',
      'Unauthorized update and delete return 403 or 404.',
    ],
    acceptanceCriteria: [
      'Changing an ID in the URL cannot access another user\'s resource.',
      'Unauthorized update and delete return 403 or 404.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'gdpr.privacy': entry({
    taskId: 'remediate.gdpr.privacy',
    title: 'Add privacy and GDPR control flows',
    category: 'gdpr',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'If users exist, privacy workflows need explicit consent, export, erasure, and retention handling.',
    recommendedApproach: [
      'Add consent tracking.',
      'Add a data export endpoint.',
      'Add erasure request or delete-account flow.',
      'Add retention policy documentation or a retention job.',
    ].join('\n'),
    likelyFiles: ['backend/routes/privacy*', 'backend/routes/export*', 'backend/jobs/*', 'backend/models/*', 'src/privacy*'],
    suggestedTests: [
      'Authenticated user can request an export of personal data.',
      'Erasure request is tracked.',
      'Privacy event is audited.',
    ],
    acceptanceCriteria: [
      'Authenticated user can request export of personal data.',
      'Erasure request is tracked.',
      'Privacy event is audited.',
    ],
    dependencies: ['remediate.auth.core'],
    supersededBy: ['expectation.gdpr.consent.required', 'expectation.gdpr.export.required', 'expectation.gdpr.erasure.required', 'expectation.gdpr.retention.recommended'],
  }),
  'observability.logging': entry({
    taskId: 'remediate.observability.logging',
    title: 'Add structured logging and request correlation',
    category: 'observability',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Structured logs and correlation ids make runtime troubleshooting and incident triage materially easier.',
    recommendedApproach: ['Add a structured logger.', 'Add request id or correlation id handling.', 'Centralize error logging.'].join('\n'),
    likelyFiles: ['backend/logger*', 'backend/middleware/*', 'src/logger*', 'src/middleware/*'],
    suggestedTests: [
      'Every request gets a request id.',
      'Server errors are logged with structured metadata.',
    ],
    acceptanceCriteria: [
      'Every request has a request id.',
      'Server errors are logged with structured metadata.',
    ],
    dependencies: [],
  }),
  'observability.health': entry({
    taskId: 'remediate.observability.health',
    title: 'Add a runtime healthcheck endpoint',
    category: 'observability',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Health endpoints are a low-risk operational baseline for orchestration and deployment checks.',
    recommendedApproach: ['Add /health or /healthz and keep the response lightweight and deterministic.'].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/app.js', 'src/server.ts', 'src/app.ts'],
    suggestedTests: [
      'Health endpoint returns 200 in a healthy runtime.',
      'Health response stays deterministic and lightweight.',
    ],
    acceptanceCriteria: [
      'Healthcheck succeeds.',
      'Health endpoint is deterministic and lightweight.',
    ],
    dependencies: [],
  }),
  'deployment.readiness': entry({
    taskId: 'remediate.deployment.readiness',
    title: 'Add reproducible deployment assets',
    category: 'deployment',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'A reproducible deploy path reduces environment drift and makes operational behavior easier to verify.',
    recommendedApproach: [
      'Add a Dockerfile.',
      'Add docker-compose for local reproducibility when useful.',
      'Add healthcheck and graceful shutdown handling.',
      'Add production env validation.',
    ].join('\n'),
    likelyFiles: ['Dockerfile', 'docker-compose.yml', 'package.json', 'src/index.ts', 'backend/server.js'],
    suggestedTests: [
      'App can be started reproducibly.',
      'Healthcheck succeeds.',
      'SIGTERM shuts down cleanly.',
    ],
    acceptanceCriteria: [
      'App can be started reproducibly.',
      'Healthcheck succeeds.',
      'SIGTERM shuts down cleanly.',
    ],
    dependencies: ['remediate.observability.health'],
  }),
  'docker.presence': entry({
    taskId: 'remediate.docker.presence',
    title: 'Add Docker packaging for repeatable runs',
    category: 'deployment',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Container packaging makes local and CI execution reproducible and reduces implicit environment drift.',
    recommendedApproach: ['Add a Dockerfile.', 'Add Compose if the app needs supporting services.', 'Keep runtime and health behavior deterministic.'].join('\n'),
    likelyFiles: ['Dockerfile', 'docker-compose.yml', 'package.json', 'src/index.ts'],
    suggestedTests: [
      'Container build succeeds.',
      'Runtime starts and exposes a healthcheck.',
    ],
    acceptanceCriteria: [
      'Container build succeeds.',
      'Runtime starts and exposes a healthcheck.',
    ],
    dependencies: ['remediate.deployment.readiness'],
  }),
  'env.example': entry({
    taskId: 'remediate.env.example',
    title: 'Document required environment variables in .env.example',
    category: 'env',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'A safe example environment file is the simplest way to document required secrets and configuration shape.',
    recommendedApproach: [
      'Add or refresh .env.example with safe placeholders only.',
      'Keep secret values out of the example file.',
      'Document the required runtime variables alongside the template.',
    ].join('\n'),
    likelyFiles: ['.env.example', 'backend/config/*', 'src/env.ts', 'src/config/*'],
    suggestedTests: [
      '.env.example contains placeholders only.',
      'Required env variables are documented.',
    ],
    acceptanceCriteria: [
      '.env.example documents required keys without real values.',
      'Secrets remain absent from the example file.',
    ],
    dependencies: [],
  }),
  'expectation.auth.required': entry({
    ...entry({
      taskId: 'remediate.auth.core',
      title: 'Implement an explicit authentication baseline',
      category: 'auth',
      phaseId: critical,
      priority: 'p0',
      effort: 'medium',
      risk: 'medium',
      automationReadiness: 'needs_review',
      why: 'A clear auth baseline is the prerequisite for protected resources, rate limits, tenant scoping, and privacy workflows.',
      recommendedApproach: [
        'Add a clear auth flow and secure credential handling.',
        'Ensure auth state is backed by explicit middleware or framework primitives.',
        'Cover login, logout, and session handling with tests.',
      ].join('\n'),
      likelyFiles: ['backend/routes/auth*', 'backend/middleware/auth*', 'src/auth*', 'src/middleware/*'],
      suggestedTests: [
        'Authenticated requests succeed and anonymous requests fail.',
        'Login/session setup is covered by tests.',
      ],
      acceptanceCriteria: [
        'Authentication flow is explicit and test-covered.',
        'Credentials and sessions are handled securely.',
      ],
      dependencies: [],
    }),
  }),
  'expectation.security.headers.required': entry({
    taskId: 'remediate.security.helmet',
    title: 'Add security headers middleware',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Helmet-style security headers are a low-risk baseline that improves browser-side hardening quickly.',
    recommendedApproach: ['Install and mount helmet before routes.', 'Tune CSP and HSTS for the deployment model.'].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/app.js', 'src/server.ts', 'src/app.ts'],
    suggestedTests: [
      'Helmet is mounted before routes.',
      'Production responses include security headers.',
    ],
    acceptanceCriteria: [
      'Helmet is mounted before routes.',
      'Production security headers are present.',
    ],
    dependencies: [],
  }),
  'expectation.security.cors.required': entry({
    taskId: 'remediate.security.cors-origin',
    title: 'Lock CORS to explicit allowed origins',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'safe_template',
    why: 'Permissive CORS can expose authenticated browser flows to unwanted cross-origin access.',
    recommendedApproach: [
      'Replace cors() defaults with an explicit allowlist.',
      'Drive allowed origins from environment variables.',
      'Reject unknown origins in production.',
    ].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/config/*', 'src/server.ts', '.env.example'],
    suggestedTests: [
      'Production CORS is not wildcard or permissive.',
      'Allowed origins are sourced from configuration.',
      'Unexpected origins are rejected.',
    ],
    acceptanceCriteria: [
      'Production CORS is not wildcard/permissive.',
      'Allowed origins are documented in .env.example.',
    ],
    dependencies: ['remediate.env.example'],
  }),
  'expectation.security.rate-limit.required': entry({
    taskId: 'remediate.security.rate-limit-auth',
    title: 'Rate limit authentication surfaces',
    category: 'security',
    phaseId: critical,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Login and password-reset endpoints are common brute-force targets and should be throttled explicitly.',
    recommendedApproach: [
      'Apply auth-specific rate limiting to login, register, and password-reset routes.',
      'Avoid throttling unrelated API traffic.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/middleware/*', 'src/routes/auth*', 'src/middleware/*'],
    suggestedTests: [
      'Repeated login attempts are throttled.',
      'Normal API routes are not unintentionally blocked.',
    ],
    acceptanceCriteria: [
      'Repeated login attempts are throttled.',
      'Normal API routes remain usable.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'expectation.uploads.required': entry({
    taskId: 'remediate.uploads.public-exposure',
    title: 'Protect public upload routes',
    category: 'uploads',
    phaseId: critical,
    priority: 'p0',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'needs_review',
    why: 'Anonymous upload exposure can lead to data leakage, abuse, and content-type bypasses.',
    recommendedApproach: [
      'Protect the /uploads static route with auth middleware.',
      'Validate MIME type and extension.',
      'Enforce maximum upload size.',
      'Prefer private object storage or signed URLs over public disk exposure.',
    ].join('\n'),
    likelyFiles: ['backend/app.js', 'backend/server.js', 'backend/routes/uploads*', 'backend/middleware/auth*'],
    suggestedTests: [
      'Anonymous access to protected uploads is denied.',
      'Oversized or invalid MIME uploads are rejected.',
      'Authenticated upload flow still works.',
    ],
    acceptanceCriteria: [
      'Uploads are not publicly exposed without auth checks.',
      'Anonymous access is denied for protected uploads.',
      'Upload validation rejects invalid files.',
    ],
    dependencies: ['remediate.auth.core'],
  }),
  'expectation.observability.health.required': entry({
    taskId: 'remediate.observability.health',
    title: 'Add a runtime healthcheck endpoint',
    category: 'observability',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Health endpoints are a low-risk operational baseline for orchestration and deployment checks.',
    recommendedApproach: ['Add /health or /healthz and keep the response lightweight and deterministic.'].join('\n'),
    likelyFiles: ['backend/server.js', 'backend/app.js', 'src/server.ts', 'src/app.ts'],
    suggestedTests: [
      'Health endpoint returns 200 in a healthy runtime.',
      'Health response stays deterministic and lightweight.',
    ],
    acceptanceCriteria: [
      'Healthcheck succeeds.',
      'Health endpoint is deterministic and lightweight.',
    ],
    dependencies: [],
  }),
  'expectation.observability.logging.recommended': entry({
    taskId: 'remediate.observability.logging',
    title: 'Add structured logging and request correlation',
    category: 'observability',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Structured logs and correlation ids make runtime troubleshooting and incident triage materially easier.',
    recommendedApproach: ['Add a structured logger.', 'Add request id or correlation id handling.', 'Centralize error logging.'].join('\n'),
    likelyFiles: ['backend/logger*', 'backend/middleware/*', 'src/logger*', 'src/middleware/*'],
    suggestedTests: [
      'Every request gets a request id.',
      'Server errors are logged with structured metadata.',
    ],
    acceptanceCriteria: [
      'Every request has a request id.',
      'Server errors are logged with structured metadata.',
    ],
    dependencies: [],
  }),
  'expectation.observability.logging.required': entry({
    taskId: 'remediate.observability.logging',
    title: 'Add structured logging and request correlation',
    category: 'observability',
    phaseId: ops,
    priority: 'p1',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'safe_template',
    why: 'Structured logs and correlation ids make runtime troubleshooting and incident triage materially easier.',
    recommendedApproach: ['Add a structured logger.', 'Add request id or correlation id handling.', 'Centralize error logging.'].join('\n'),
    likelyFiles: ['backend/logger*', 'backend/middleware/*', 'src/logger*', 'src/middleware/*'],
    suggestedTests: [
      'Every request gets a request id.',
      'Server errors are logged with structured metadata.',
    ],
    acceptanceCriteria: [
      'Every request has a request id.',
      'Server errors are logged with structured metadata.',
    ],
    dependencies: [],
  }),
  'expectation.deployment.required': entry({
    taskId: 'remediate.deployment.readiness',
    title: 'Add reproducible deployment assets',
    category: 'deployment',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'A reproducible deploy path reduces environment drift and makes operational behavior easier to verify.',
    recommendedApproach: [
      'Add a Dockerfile.',
      'Add docker-compose for local reproducibility when useful.',
      'Add healthcheck and graceful shutdown handling.',
      'Add production env validation.',
    ].join('\n'),
    likelyFiles: ['Dockerfile', 'docker-compose.yml', 'package.json', 'src/index.ts', 'backend/server.js'],
    suggestedTests: [
      'App can be started reproducibly.',
      'Healthcheck succeeds.',
      'SIGTERM shuts down cleanly.',
    ],
    acceptanceCriteria: [
      'App can be started reproducibly.',
      'Healthcheck succeeds.',
      'SIGTERM shuts down cleanly.',
    ],
    dependencies: ['remediate.observability.health'],
  }),
  'expectation.docker.recommended': entry({
    taskId: 'remediate.docker.presence',
    title: 'Add Docker packaging for repeatable runs',
    category: 'deployment',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Container packaging makes local and CI execution reproducible and reduces implicit environment drift.',
    recommendedApproach: ['Add a Dockerfile.', 'Add Compose if the app needs supporting services.', 'Keep runtime and health behavior deterministic.'].join('\n'),
    likelyFiles: ['Dockerfile', 'docker-compose.yml', 'package.json', 'src/index.ts'],
    suggestedTests: [
      'Container build succeeds.',
      'Runtime starts and exposes a healthcheck.',
    ],
    acceptanceCriteria: [
      'Container build succeeds.',
      'Runtime starts and exposes a healthcheck.',
    ],
    dependencies: ['remediate.deployment.readiness'],
  }),
  'expectation.audit.recommended': entry({
    taskId: 'remediate.audit.baseline',
    title: 'Add audit logging for sensitive actions',
    category: 'audit',
    phaseId: ops,
    priority: 'p2',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Sensitive actions should be traceable for compliance, support, and incident response.',
    recommendedApproach: [
      'Log auth, billing, admin, privacy, and destructive actions.',
      'Capture actor, action, target, timestamp, and request id.',
      'Avoid storing sensitive payload data in audit events.',
    ].join('\n'),
    likelyFiles: ['backend/middleware/*', 'backend/services/*', 'backend/routes/*', 'src/middleware/*'],
    suggestedTests: [
      'Sensitive actions generate audit entries.',
      'Audit entries include actor/action/target/request id/timestamp.',
      'Sensitive payloads are not persisted in audit logs.',
    ],
    acceptanceCriteria: [
      'Sensitive actions are auditable.',
      'Audit entries contain required context fields.',
      'Sensitive payloads are excluded from audit logs.',
    ],
    dependencies: [],
  }),

  // --- Capabilities split out of the former coarse expectations -------------
  // `expectation.tenancy.required`, `expectation.gdpr.required` and
  // `expectation.authz.resource-level.required` no longer exist: each is now a
  // granular capability with its own finding id, so each needs its own task.

  'expectation.tenancy.organization.required': entry({
    taskId: 'remediate.tenancy.organization',
    title: 'Introduce an explicit organization model',
    category: 'tenancy',
    phaseId: safety,
    priority: 'p0',
    effort: 'large',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'Without an organization entity that owns data, every record belongs to the whole system and there is nothing to scope access by.',
    recommendedApproach: [
      'Introduce an Organization (or Workspace) model as the owner of domain records.',
      'Add organizationId to every tenant-owned table with a migration.',
      'Resolve the active organization in request context.',
    ].join('\n'),
    likelyFiles: ['backend/models/*', 'backend/middleware/*', 'migrations/*', 'src/db/*'],
    suggestedTests: [
      'Domain records carry an organization reference.',
      'Request context resolves the active organization.',
    ],
    acceptanceCriteria: [
      'An organization entity exists and owns domain records.',
      'Every tenant-owned table references the organization.',
    ],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.tenancy.isolation.required': entry({
    taskId: 'remediate.tenancy.isolation',
    title: 'Enforce tenant isolation on every query',
    category: 'tenancy',
    phaseId: safety,
    priority: 'p0',
    effort: 'large',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'An organization model without enforced scoping still leaks: one tenant can read another tenant rows by guessing identifiers.',
    recommendedApproach: [
      'Model Membership explicitly and check it on access.',
      'Scope every query by the active tenant rather than filtering in application code.',
      'Add cross-tenant access tests as a regression guard.',
    ].join('\n'),
    likelyFiles: ['backend/middleware/*', 'backend/routes/*', 'backend/services/*', 'src/db/*'],
    suggestedTests: [
      'A user of tenant A cannot read, update or delete a record of tenant B.',
      'Membership is required to access organization data.',
    ],
    acceptanceCriteria: [
      'Cross-tenant access is rejected and covered by tests.',
      'Tenant membership is explicit.',
    ],
    dependencies: ['remediate.tenancy.organization'],
  }),

  'expectation.authz.roles.required': entry({
    taskId: 'remediate.authz.roles',
    title: 'Introduce a role or permission model',
    category: 'authz',
    phaseId: safety,
    priority: 'p0',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'Without roles, every authenticated user can perform every action, including administrative and destructive ones.',
    recommendedApproach: [
      'Define roles (or permissions) and assign them to users within their tenant.',
      'Check the role on privileged and destructive actions.',
    ].join('\n'),
    likelyFiles: ['backend/models/*', 'backend/middleware/*', 'backend/routes/*'],
    suggestedTests: [
      'A member role cannot perform owner-only actions.',
      'Role checks are enforced server-side.',
    ],
    acceptanceCriteria: [
      'Distinct roles exist and are enforced on privileged actions.',
    ],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.authz.ownership.required': entry({
    taskId: 'remediate.authz.ownership',
    title: 'Add per-record ownership checks',
    category: 'authz',
    phaseId: safety,
    priority: 'p0',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'Route-level authentication without record-level checks allows a valid user to act on another user records by changing an identifier.',
    recommendedApproach: [
      'Check ownership or membership for the specific record on read, update and delete.',
      'Prefer scoped queries over post-hoc comparison.',
    ].join('\n'),
    likelyFiles: ['backend/routes/*', 'backend/services/*', 'backend/policies/*'],
    suggestedTests: [
      'Requesting another user record by id returns 403 or 404.',
    ],
    acceptanceCriteria: [
      'Read, update and delete verify the caller may act on that specific record.',
    ],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.gdpr.consent.required': entry({
    taskId: 'remediate.gdpr.consent',
    title: 'Capture and store consent',
    category: 'gdpr',
    phaseId: safety,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Processing personal data needs a recorded lawful basis, and consent that is not stored cannot be demonstrated later.',
    recommendedApproach: [
      'Record consent with timestamp, subject and the version of the terms accepted.',
      'Expose the current consent state to the user.',
    ].join('\n'),
    likelyFiles: ['backend/models/*', 'backend/routes/privacy*', 'src/privacy*'],
    suggestedTests: ['Consent is persisted with timestamp and terms version.'],
    acceptanceCriteria: ['Consent is recorded and retrievable per user.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.gdpr.export.required': entry({
    taskId: 'remediate.gdpr.export',
    title: 'Add a personal data export endpoint',
    category: 'gdpr',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'GDPR article 20 gives users the right to obtain their personal data in a machine-readable form.',
    recommendedApproach: [
      'Add an authenticated export endpoint that gathers user data across stores.',
      'Produce a machine-readable archive and audit the request.',
    ].join('\n'),
    likelyFiles: ['backend/routes/export*', 'backend/services/*', 'backend/jobs/*'],
    suggestedTests: ['An authenticated user can export their own data and only their own.'],
    acceptanceCriteria: ['Export returns the user personal data in a machine-readable format.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.gdpr.erasure.required': entry({
    taskId: 'remediate.gdpr.erasure',
    title: 'Add an account erasure flow',
    category: 'gdpr',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'high',
    automationReadiness: 'manual_only',
    why: 'GDPR article 17 requires deletion of personal data on request, across every store that holds it.',
    recommendedApproach: [
      'Add a delete-account flow that removes or anonymises personal data.',
      'Cover derived stores: caches, search indexes, backups policy, logs.',
      'Audit the erasure request and its completion.',
    ].join('\n'),
    likelyFiles: ['backend/routes/privacy*', 'backend/services/*', 'backend/jobs/*'],
    suggestedTests: ['Erasure removes or anonymises the user across primary and derived stores.'],
    acceptanceCriteria: ['An erasure request is tracked and demonstrably completed.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.gdpr.retention.recommended': entry({
    taskId: 'remediate.gdpr.retention',
    title: 'Define and enforce retention limits',
    category: 'gdpr',
    phaseId: ops,
    priority: 'p2',
    effort: 'small',
    risk: 'low',
    automationReadiness: 'needs_review',
    why: 'Personal data kept indefinitely by default increases breach impact and weakens the lawful basis for processing.',
    recommendedApproach: [
      'Define a retention window per data category.',
      'Run a scheduled job that deletes or anonymises data past its window.',
    ].join('\n'),
    likelyFiles: ['backend/jobs/*', 'backend/config/*'],
    suggestedTests: ['Data past its retention window is removed by the job.'],
    acceptanceCriteria: ['Retention windows are defined and enforced by a job.'],
    dependencies: [],
  }),

  'expectation.auth.password-reset.required': entry({
    taskId: 'remediate.auth.password-reset',
    title: 'Add a password reset flow',
    category: 'auth',
    phaseId: safety,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Without self-service recovery every locked-out user becomes a support request, and ad-hoc manual resets become their own attack surface.',
    recommendedApproach: [
      'Issue a single-use, expiring reset token delivered out of band.',
      'Invalidate active sessions on a successful reset.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/services/auth*'],
    suggestedTests: [
      'A reset token works once and expires.',
      'Sessions are invalidated after a reset.',
    ],
    acceptanceCriteria: ['Users can recover access without operator intervention.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.auth.email-verification.required': entry({
    taskId: 'remediate.auth.email-verification',
    title: 'Verify email ownership at signup',
    category: 'auth',
    phaseId: safety,
    priority: 'p1',
    effort: 'small',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Unverified addresses allow impersonation of an address the signup does not control, and make abuse cheap.',
    recommendedApproach: [
      'Send a verification token and gate full account capabilities until it is used.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/services/auth*'],
    suggestedTests: ['An unverified account cannot use gated capabilities.'],
    acceptanceCriteria: ['Email ownership is proven before full access is granted.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.auth.mfa.required': entry({
    taskId: 'remediate.auth.mfa',
    title: 'Offer a second authentication factor',
    category: 'auth',
    phaseId: safety,
    priority: 'p1',
    effort: 'medium',
    risk: 'medium',
    automationReadiness: 'needs_review',
    why: 'Accounts that move money or administer other users are worth stealing, and a password alone is a single point of failure.',
    recommendedApproach: [
      'Support TOTP or WebAuthn as a second factor.',
      'Require it at least for owner and admin roles.',
      'Provide recovery codes and audit their use.',
    ].join('\n'),
    likelyFiles: ['backend/routes/auth*', 'backend/services/auth*', 'backend/models/*'],
    suggestedTests: [
      'An account with MFA enabled requires the second factor.',
      'Recovery codes work once.',
    ],
    acceptanceCriteria: ['A second factor is available and enforceable for privileged roles.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.billing.model.required': entry({
    taskId: 'remediate.billing.model',
    title: 'Introduce a billing and entitlement model',
    category: 'billing',
    phaseId: safety,
    priority: 'p1',
    effort: 'large',
    risk: 'medium',
    automationReadiness: 'manual_only',
    why: 'A product that charges needs plans and server-side entitlement checks, otherwise paid features are only hidden, not protected.',
    recommendedApproach: [
      'Model plans and subscriptions.',
      'Check entitlement server-side on every paid capability.',
    ].join('\n'),
    likelyFiles: ['backend/models/*', 'backend/services/billing*', 'backend/routes/*'],
    suggestedTests: ['A free-plan account cannot reach a paid capability by calling the API directly.'],
    acceptanceCriteria: ['Entitlement is enforced server-side, not only in the UI.'],
    dependencies: ['remediate.auth.core'],
  }),

  'expectation.billing.webhook-integrity.required': entry({
    taskId: 'remediate.billing.webhook-integrity',
    title: 'Verify payment webhook signatures',
    category: 'billing',
    phaseId: critical,
    priority: 'p0',
    effort: 'small',
    risk: 'high',
    automationReadiness: 'safe_template',
    why: 'An unverified payment webhook lets anyone forge a request that grants a paid plan for free, or marks an unpaid order as paid.',
    recommendedApproach: [
      'Verify the provider signature against the raw, unparsed request body.',
      'Load the signing secret from configuration with no fallback default.',
      'Reject and log requests that fail verification.',
    ].join('\n'),
    likelyFiles: ['backend/routes/webhook*', 'backend/routes/stripe*', 'src/app/api/webhook*'],
    suggestedTests: [
      'A request with an invalid signature is rejected.',
      'The raw body is used for verification, not the parsed one.',
    ],
    acceptanceCriteria: ['Only signature-verified webhook events change billing state.'],
    dependencies: [],
  }),
};

/**
 * Expectation findings carry their importance in the id
 * (`expectation.auth.mfa.required` vs `...recommended`), but the remediation work is
 * the same either way — only the urgency differs, and that is already carried by the
 * finding severity. Falling back across the importance suffix avoids duplicating every
 * catalogue entry once per profile that grades the capability differently.
 */
const IMPORTANCE_SUFFIXES = ['.required', '.recommended'] as const;

export function getRemediationEntry(findingId: string): RemediationCatalogEntry | undefined {
  const exact = remediationCatalog[findingId];
  if (exact) return exact;

  for (const suffix of IMPORTANCE_SUFFIXES) {
    if (!findingId.endsWith(suffix)) continue;

    const stem = findingId.slice(0, -suffix.length);
    for (const alternative of IMPORTANCE_SUFFIXES) {
      if (alternative === suffix) continue;

      const candidate = remediationCatalog[`${stem}${alternative}`];
      if (candidate) return candidate;
    }
  }

  return undefined;
}
