plugins {
    id 'java'
}

ext {
    jettyVersion = "12.1.12"
    jerseyVersion = "4.0.2"
}

dependencies {
    implementation "org.eclipse.jetty:jetty-server:$jettyVersion"
    implementation "org.eclipse.jetty.ee10:jetty-ee10-servlet:$jettyVersion"
    implementation "org.glassfish.jersey.containers:jersey-container-servlet:$jerseyVersion"
    implementation "org.glassfish.jersey.media:jersey-media-json-jackson:$jerseyVersion"
    implementation "org.postgresql:postgresql:42.7.4"
    implementation "com.sun.mail:jakarta.mail:2.0.2"
}
